### ISSUE TITLE
Zip em Git não é muito amigável às ferramentas Open Source

### ISSUE THREAD

**Issue by LaPingvino** [carrismetropolitana/gtfs#1]
**Descrição**  
Por agora as informações ficam com .zip em GitHub, que deixa muito difícil ver as adaptações com o tempo etc. Se calhar funciona melhor disponibilizar o conteúdo dos .zip em pastas, e disponibilizar os .zip como release, ou mesmo ter 4 repositórios, um para cada área e com o conteúdo do zip, assim que a opção baixar o .zip do master já funcione como gtfs...

**Comment by joao-vasconcelos** [comment]
Olá @LaPingvino, obrigado pelo comentário! De facto essa seria a melhor opção. No entanto, alguns ficheiros do GTFS (stop_times.txt) são superiores ao limite do Github. Daí não terem sido colocadas as pastas abertas. Neste momento, o objetivo de colocar o GTFS no Github é disponibilizar uma única versão para todos os interessados, permitindo atualizações frequentes, comentadas, preservando o histórico destas atualizações.

**Comment by LaPingvino** [comment]
Se calhar nos dias seguintes posso experimentar um pouco com isso, talvez até o Github mesmo pode ajudar com isso... De todas as formas também poderia considerar por exemplo o Codeberg, que é mesmo para projeto aberto e usa o Forgejo (Gitea mas aos poucos a ser adaptado para incluir opções de federação), até no longo prazo poderiam considerar rodar uma versão do Forgejo em domínio da TML para este fim...

Agradeço muito pelo trabalho incrível! Como eu já disse ao motorista no 1718 até Belém: agora ainda tem muita coisa que poderia melhorar, mas é muito possível que ao chegar no verão a Carris Metropolitana funcione melhor do que a própria Carris xD. Agora o passo seguinte também será o real-time?

(aliás, um pouco fora do assunto, mas por acaso teria também uma lista de linhas previstas para abrir ainda no futuro, principalmente na área 3? eu vi por exemplo o 3708 Costa da Caparica - Cais do Sodré que ainda não anda e tem um bocado mais...)

**Comment by claudioap** [comment]
@LaPingvino Enquanto que concordo consigo, para esta altura talvez seja boa ideia serem pragmáticos e o GitHub (do qual também confesso não gostar muito) acaba por ser o mais acessível devido à familiaridade da maior parte das pessoas que fariam uso destes dados.

Quer-me parecer que a Carris Metropolitana ainda se encontra a pagar dívida técnica, o que é senão natural. Foi notório que tinham imensos problemas há uns meses e progressivamente tem vindo a colocar o essencial no sítio, cada vez melhor. Agora que estes dados estáticos já foram abertos, quem sabe é sensato assumir que nos próximos meses virão a libertar mais e melhor informação. O tempo dirá.

**Comment by joao-vasconcelos** [comment]
Neste momento o Github é ideal para permitir um URL público e estável para cada GTFS. É flexível e permite facilmente manter a informação atualizada. Vamos manter este sistema por enquanto, mas explorar as sugestões.

Relativamente às linhas, não tenho essa informação neste momento. No entanto, o GTFS é frequentemente atualizado com novas linhas e ajustes de horários.

Vou dar este issue como terminado, _not solved_, uma vez que vamos manter o sistema atual. Caso faça sentido, abrimos novamente. Obrigado pelas boas sugestões!
