### ISSUE TITLE
Gralha em paragem no Bairro Mato Antão

### ISSUE THREAD

**Issue by ScriptForAll** [carrismetropolitana/gtfs#10]
**Descreva o erro**  
Na paragem com identificador 070231 aparece a gralha "Manto Antão".

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [x] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
_Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida._

Passar de "Manto Antão" para "Mato Antão" tal como é a toponímia do bairro.

**Screenshots**  
_Se fizer sentido, adicione imagens que ajudem a explicar o problema._
NA

**Contexto adicional**  
_Adicione qualquer outra informação útil à resolução do problema._
NA

**Comment by DiogoBaptista98** [comment]
Este erro já se encontra resolvido no GTFS @joao-vasconcelos

**Comment by patriciataborda** [comment]
Vamos transmitir ao operador para corrigir a gralha no postalete.

Obrigada
