### ISSUE TITLE
[A3] Remoção de paragem 020921

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#101]
A3 
Foi criada a nova paragem 020606 tendo sido esquecida a remoção da antiga 020921 que contem as mesmas linhas e que dista meros 30 metros da nova. 

![image](https://user-images.githubusercontent.com/54463127/236239098-18600a7a-eedf-419f-91cf-d16b480a4009.png)

**Comment by joao-vasconcelos** [comment]
[Link Horários](https://www.carrismetropolitana.pt/horarios/?route_short_name=3510&date=2023-05-16&municipality_id=&route_id=3510_0&direction_id=1&trip_id=p2_3510_0_2_2130_2159_0_ESC_DU&stop_id=020921&stop_sequence=8)

**Comment by DiogoBaptista98** [comment]
> [Link Horários](https://www.carrismetropolitana.pt/horarios/?route_short_name=3510&date=2023-05-16&municipality_id=&route_id=3510_0&direction_id=1&trip_id=p2_3510_0_2_2130_2159_0_ESC_DU&stop_id=020921&stop_sequence=8)

Com a criação e organização das linhas na paragem  020606  não se eliminou esta antiga. Esta issue foi criada pela enorme proximidade entre ambas as paragens situação algo caricata reportada a mim por um motorista do operador que faz esta linha.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada! Já corrigimos, entretanto fica disponível no site.
