### ISSUE TITLE
Licença para uso dos dados

### ISSUE THREAD

**Issue by alex9099** [carrismetropolitana/gtfs#102]
De acordo com https://www.carrismetropolitana.pt/opendata/ dá a entender que os dados disponibilizados tem uma licença equiparada a domínio publico, dado que não refere quaisquer limitações ao seu uso nem necessidade de atribuição.

No caso, o objetivo seria importação dos dados na plataforma openstreetmap, a qual obriga a uma licença (ou autorização) que permita o uso livre dos dados sem necessidade de atribuição e que permita o seu uso comercial.

Posto isto, qual seria a licença aplicável a este repositório?

**Comment by joao-vasconcelos** [comment]
Olá @alex9099! Por publicarmos o GTFS também nos [DadosGOV](https://dados.gov.pt/pt/docs/licenses/) e por a licença sugerida por essa plataforma ser a CC-BY-4.0, adicionámos aqui ao repo essa informação. Obrigado!
