### ISSUE TITLE
[A3] Falta paragem 3024

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#104]
A3
A linha 3024 falha as paragens 029001 e 029002 cada uma para cada sentido, passando pelas mesmas sem fazer serviço.
Pede-se por isso que sejam adicionadas as paragens descritas a esta linha.

![image](https://user-images.githubusercontent.com/54463127/236715668-375c34cd-a838-4a44-b27e-22c48896be8b.png)

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98 , obrigada pelo alerta. A situação já se encontra corrigida e disponível no site.
