### ISSUE TITLE
[A1] Ajuste de paragem 1102

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#105]
A1
Sugere-se que se atualize a linha 1102 no sentido Algés Junça (Centro Comercial) (ex Combus que por isso não partilhava os mesmo abrigos que outros operadores) a fazer paragem na 121045 servindo a zona de Algés de Cima, área que atualmente esta linha atravessa mas sem a servir. 
![image](https://user-images.githubusercontent.com/54463127/236879074-09cd6fff-7c9c-442c-b375-dd08e9747976.png)

**Comment by aquint96** [comment]
Bom dia, agradecemos a sugestão caso haja necessidade de alteração iremos, em conjunto com o operador, analisar a situação, obrigado.
