### ISSUE TITLE
[A1] Paragem em falta - Rua da Eira 4

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#106]
A1
Foi encontrada a paragem abaixo indicada que não consta no ficheiro de dados, a paragem em questão que corresponde à antiga paragem Rua da Eira 4 da linha Combus hoje 1102 e que só apresenta poste, sem postalete, nome ou numero de referencia, e dista meros 100 metros da paragem R da Eira 11 120211 que pertence à mesma rota (1102) pelo que de pode ou não ponderar a sua não ativação e remoção.
![image](https://user-images.githubusercontent.com/54463127/236881255-91eecea6-51f4-4de6-9a74-3c0a92a2a357.png)

**Comment by aquint96** [comment]
Bom dia, o operador informou-nos que o poste já foi retirado do local, obrigado.
