### ISSUE TITLE
Correção na paragem 120238 - Linhas 1102, 1724, 1728, 1730

### ISSUE THREAD

**Issue by Gasosa12** [carrismetropolitana/gtfs#108]
**Descreva o erro**  

As coordenadas corretas da paragem 120238 R Ceuta 23a (Centro de saúde) devem ser 38.714612, -9.235022.

Nesta paragem devem parar as seguintes linhas:
- 1102 - Sentido Algés Junça (C. Comercial);
- 1724 - Apenas variante com destino ao Marquês de Pombal (Metro) (Circular via Linda-a-Velha);
- 1728 - Todas as variantes existentes tanto no sentido Queijas (PSP) como no sentido Marquês de Pombal (Metro);
- 1730 - Apenas variantes com destino a:
Queluz de Baixo (C. Comercial) (via Linda-a-velha),
Queluz de Baixo (C. Comercial) (via Linda-a-velha e Alto Stª Catarina),
Marquês de Pombal (Metro) (via Linda-a-velha).

Deve também ser criada uma paragem nas coordenadas 38.714646, -9.234839 mesmo junto ao centro de saúde para a linha 1102 no sentido Cruz Quebrada (Piscinas) pois esta linha substituiu a antiga linha COMBUS que tinha uma paragem neste local.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [x] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Comment by DiogoBaptista98** [comment]
@Gasosa12 para perceber melhor tem foto para ver onde se encontra a paragem 120238? Obrigado

**Comment by Gasosa12** [comment]
@DiogoBaptista98 eu ainda não estive pessoalmente neste local, mas tendo em conta o nome que foi dado à paragem vou assumir que ela está no local correto mas que o GTFS tem as coordenadas erradas até porque antes da entrada em funcionamento da Carris Metropolitana a Vimeca andou a substituir as paragens existentes pelos novos postes amarelos e não acredito que alguém tenha chegado lá, retirado o poste antigo e colocado o poste amarelo novo no lado oposto da rua.

**Comment by joao-vasconcelos** [comment]
@Gasosa12 obrigado pelo feedback. Foi corrigida a localização da paragem `120238` e deverá atualizar em breve no site e apps. Sobre as linhas que devem parar na `120238` é uma sugestão ou os veículos já lá param? Sobre a nova paragem, esta não existe no local, correto?

**Comment by DiogoBaptista98** [comment]
> @Gasosa12 obrigado pelo feedback. Foi corrigida a localização da paragem `120238` e deverá atualizar em breve no site e apps. Sobre as linhas que devem parar na `120238` é uma sugestão ou os veículos já lá param? Sobre a nova paragem, esta não existe no local, correto?

A nova paragem corresponde à antiga da Combus que não chegou a ser colocada, a paragem é fundamental para a linha 1102 sentido Cruz Quebrada que foi colocada errada no ponto `120238`
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/0b26f79c-8ee6-4f88-b23d-bdedc94e07cc)

**Comment by Gasosa12** [comment]
> @Gasosa12 obrigado pelo feedback. Foi corrigida a localização da paragem `120238` e deverá atualizar em breve no site e apps. Sobre as linhas que devem parar na `120238` é uma sugestão ou os veículos já lá param? Sobre a nova paragem, esta não existe no local, correto?

Hoje estava por perto então passei lá no local para ver que paragens estavam lá. A paragem 120238 está no local que eu indiquei, por isso o GTFS tinha a localização errada que entretanto já foi corrigida.

Em relação às linhas que lá devem parar, a bandeira da paragem tem apenas os números das linhas 1102 e 1728, no entanto reparei que alguns números estavam tapados com um autocolante preto (possivelmente os números 1724 e 1730 visto que são as outras duas linhas que passam naquela rua), na placa onde os horários estão afixados também estavam lá mais horários que aqueles que era suposto se só parassem ali as linhas 1102 e 1728. Ou seja, as linhas 1724 e 1730 era suposto pararem ali também, mas não param porque os números foram tapados e removidos daquela paragem no GTFS, apesar dos horários terem ficado lá afixados à mesma.

Devo mencionar também que as linhas 1728 e 1730 fazem exatamente o mesmo percurso entre o Marquês de Pombal e Queijas sendo que a 1730 depois continua o seu percurso até Queluz de Baixo e que estas duas linhas substituem a linha 1724 no período noturno, daí não fazer sentido que não parem ali todas, por isso isto não é uma sugestão, existe aqui um erro.

Em relação à nova paragem da linha 1102, não estava lá nenhum postalete amarelo.

**Comment by aquint96** [comment]
Boa tarde, informamos que a paragem junto ao centro de saúde já se encontra no local, servindo a linha 1102.

**Comment by Gasosa12** [comment]
Olá @aquint96, obrigado por resolverem a questão da paragem em falta, no entanto esta situação ainda não está 100% resolvida, a paragem que já existia naquela rua, e que agora penso que tem o código 120237, continua a não ter lá o numero da linha 1724. Os únicos números que estão lá são os 1102, 1728 e 1730 (este ultimo adicionado recentemente). A linha 1724 também deve servir esta paragem mas apenas aos fins de semana pois ela faz um percurso ligeiramente diferente do percurso dos dias uteis que não lhe permite servir a paragem 121257 existente na rua R Dr. Agostinho Campos.

Este é o percurso feito aos Dias Uteis
![LAV DUT edit](https://github.com/carrismetropolitana/gtfs/assets/132413037/a2e28b56-b7c7-472c-9040-71dd8df6fe37)

Este é o percurso feito aos fins de semana, como se pode ver a linha 1724 percorre toda a Rua de Ceuta não conseguindo servir a paragem da Rua Dr. Agostinho Campos, em substituição deve servir a paragem da Rua de Ceuta.
![LAV Circ edit](https://github.com/carrismetropolitana/gtfs/assets/132413037/3a299daf-aefa-495d-9e73-c0917dc1c532)

**Comment by aquint96** [comment]
Bom dia @Gasosa12, relativamente à questão colocada acima não vemos como a mesma pode ser viável, visto que ao fim-de-semana o Centro de Saúde está fechado, e até ao momento não tivemos qualquer reclamação.. Outro motivo é pelo critério usado para acrescentar paragem a uma linha, a distância para as 2 já existentes na Rua de Ceuta é de 300m, não seria benéfico para a própria viagem estar a parar em 3 paragens seguidas. 
Obrigado mais uma vez.

**Comment by Gasosa12** [comment]
Olá @aquint96, eu não concordo com a vossa decisão, eu genuinamente achava que isto tinha sido algum lapso na criação da paragem visto que a antiga linha 11 sempre parou ali, mas já percebi que foi propositado por isso não vou insistir mais neste assunto. Ainda assim, obrigado pelo esclarecimento.

**Comment by DiogoBaptista98** [comment]
> não tivemos qualquer reclamação.. Outro motivo é pelo critério usado para acrescentar paragem a uma linha, a distância para as 2 já existentes na Rua de Ceuta é de 300m, não seria benéfico para a própria viagem estar a parar em 3 paragens seguidas.
> Obrigado mais uma vez.

Na linha 1728 aos fins de semana esse argumento não prossegue. Por uma questão de uniformização do serviço e cumprimento do argumento acima indicado ou ser colocariam todas as linhas ou se retirariam todas.
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/64fcfcd7-ef73-44b0-84fe-4b95c044e355)
