### ISSUE TITLE
Pedido de informação

### ISSUE THREAD

**Issue by edgarzeferino** [carrismetropolitana/gtfs#11]
Boa noite João, na sequência da nossa conversa, na reunião do passado 2023/03/24, estive a analisar os ficheiros gtfs.
É possível ajudar-me com algumas dúvidas?
Possuem uma descrição das tabelas (eu tenho dúvidas nalguns campos)?  Caso exista, é possível disponibilizar?
Caso não haja uma descrição dos campos, referida acima, é possível indicar-me como consigo saber se um determinado horário é de que período? (escolar ou férias ou verão) e ("dia úteis" ou "sábado" ou "domingo")?

Obrigado

**Comment by claudioap** [comment]
> Possuem uma descrição das tabelas (eu tenho dúvidas nalguns campos)?

O GTFS é um formato padronizado. O significado dos campos pode ser visto aqui: https://gtfs.org/schedule/reference/

> como consigo saber se um determinado horário é de que período? (escolar ou férias ou verão) e ("dia úteis" ou "sábado" ou "domingo")?

Penso que está largamente definido por via do `calendar_dates.txt`.

PS: Não sou da TML. Só estou a tentar ajudar.

**Comment by joao-vasconcelos** [comment]
Bom dia @edgarzeferino, os períodos podem ser consultados nas colunas `period` e `day_type` no ficheiro `calendar_dates.txt`.

Legenda:

`period`
1 = Escolar
2 = Férias
3 = Verão

`day_type`
1 = Dia útil
2 = Sábado
3 = Domingo ou Feriado
