### ISSUE TITLE
Linhas 1520, 1521 e 1731 - Horários diferentes em 3 sítios

### ISSUE THREAD

**Issue by FilipeL1495** [carrismetropolitana/gtfs#113]
**Descrição**  
No site da Carris Metropolitana, os horários das linhas 1520, 1521 e 1731 (Algés-Cacém, via Porto Salvo - 3 variantes) aparecem com 3 horários distintos: um no PDF, outro no aviso da alteração e ainda um terceiro no próprio site.

**Área(s) afetada(s)**  
A sugestão é relativa a que áreas?

- [x] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Screenshots**  
Se fizer sentido, adicione imagens que ajudem a passar a mensagem.

**Contexto adicional**  
Adicione qualquer outra informação útil.

**Comment by joao-vasconcelos** [comment]
Boa tarde @FilipeL1495, esta questão deverá estar já atualizada nos horários para bater certo com o aviso (https://github.com/carrismetropolitana/gtfs/commit/904cfa05359b2e4604b80583894d60abd50f8fd3). Os PDFs aguardam atualização. Assim que ficarem atualizados dou novidades.
