### ISSUE TITLE
[A1] Paragens linha 1012

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#114]
Recentemente foi ajustado o percurso desta linha passando a ir até à estação de Alfornelos, a shape da rota não está correta pois a 1012 servia a paragem 030421, pede-se por isso se coloque a shape via R Damião Góis incluído servirem as paragens 030421 e 030397 (nova) que ficaram de fora. 
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/8246688f-b26d-4321-b0c9-4403fba9a3ec)

**Comment by Gasosa12** [comment]
Por acaso acho que faria mais sentido se esta linha passasse a servir a Rua Capitães de Abril em ambos os sentidos em vez da Rua Damião de Góis visto que atualmente não passa ali nenhuma linha e existem ali 2 escolas e umas piscinas municipais bem como vários apartamentos.

**Comment by DiogoBaptista98** [comment]
> Por acaso acho que faria mais sentido se esta linha passasse a servir a Rua Capitães de Abril em ambos os sentidos em vez da Rua Damião de Góis visto que atualmente não passa ali nenhuma linha e existem ali 2 escolas e umas piscinas municipais bem como vários apartamentos.

Tambem pensei nessa opção mas ai implicaria a criação de novas paragens. A issue foi no sentido de usar o que já existe.

**Comment by aquint96** [comment]
Bom dia, informamos que a partir do dia 1 de julho a linha 1012 passará a realizar paragem na R. Capitães de Abril na seguinte localização: 38.762500, -9.207249 

Obrigado.
