### ISSUE TITLE
[A4] Nome stops 090247 e 090248

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#116]
Foi alterado o formado do nome das paragens 090247 e 090248 quando anteriormente estava correspondente com o do postalete, devendo ter ficado por isso Baixa da Banheira (R Ville Plaisir 28)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/41099fd4-69aa-420e-b282-fba18a9deb6d)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/78ce06d7-13d8-4d06-8e2b-87b528a455b9)

**Comment by joao-vasconcelos** [comment]
Olá @DiogoBaptista98, a alteração efetuada está correta. Como deves ter reparado no GTFS e na tabela das paragens, existe o campo `locality` onde é possível colocar o nome das localidades. Este será um processo lento e gradual. Ainda, nem sempre o que está colocado no postalete é o correto. Estamos a utilizar o Intermodal para conseguir destacar as diferenças de nomenclatura entre postaletes e GTFS.
