### ISSUE TITLE
Correção de coordenadas no GTFS em várias paragens na Área 1

### ISSUE THREAD

**Issue by Gasosa12** [carrismetropolitana/gtfs#118]
**Descreva o erro**  
Deixo aqui uma lista de várias paragens que devem ter as suas coordenadas alteradas no GTFS por forma a que apareçam no mapa nas suas localizações corretas, pois atualmente elas aparecem um pouco longe ou do lado errado das ruas onde se situam.

Lista de paragens e coordenadas corretas:
`030131` Av Fernando Valle 50 (38.767575, -9.235918)
`030133` R Franc Bugalho (X) Pcta Teix Gomes (38.767873, -9.234149)
`030134` R F Bugalho (X) R Daniel Filipe (38.768001, -9.234071)
`030155` Amadora Este (Metro) (38.758253, -9.218819)
`030269` R Alberto da Conceição Guerreiro 11 (38.779746, -9.224408)
`030270` R Alberto da Conceição Guerreiro 9b (38.779539, -9.224401)
`030317` Amadora (Estação Sul) (38.758108, -9.234760)
`030319` R Elias Garcia (Parque) (38.758866, -9.237076)
`030475` R Elias Garcia 362 (38.759287, -9.237935)
`030477` R Luís Camões 9 (CTT) (38.757238, -9.236123)
`030620` Av D Nuno Álvares perreira 54 (38.758572, -9.244740)
`030621` Av D Nuno Álvares Pereira 35 (38.758574, -9.244299)
`120227` Algés - Pça D Manuel I (38.700024, -9.228518)
`170573` R Victor Cordon 5a (38.776155, -9.265701)
`170906` Av 25 Abril 18B (38.751659, -9.279280)
`170951` Idanha (Urb Campinas) (38.768630, -9.274311)
`170960` Estr Mirante 26 (38.772136, -9.270808)
`171083` Av Portugal (X) Impasse Filândia (38.767118, -9.273013)
`171084` Av Portugal (X) Impasse Filândia (38.767196, -9.273013)
`171551` Casal Cambra (R Sta Marta 22) (38.798798, -9.232982)

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Comment by claudioap** [comment]
Boa noite @Gasosa12 ,

A TML contratou recentemente a equipa do projecto Intermodal.pt (da qual faço parte) para corrigir os meta-dados da rede. Os dados obtidos por este projeto são colocados no OpenStreetMap e simultaneamente submetidos à TML. Longe de estar tudo obtido, poderá verificar que as paragens que assinalou já se encontram corrigidas, cabendo-nos agora coordenar com a TML (e por sua vez da TML com os operadores) a integração numa futura revisão de GTFS.

Ainda assim agradecemos muito o seu contributo. Conforme indicamos, ainda estamos algo distantes dos 100% de dados levantados.

Caso encontre mais erros e caso não se importe de **autorizar à TML que fique com as suas alterações**, poderá tomar a liberdade de corrigir a posição das paragens no OpenStreetMap. Algum de nós tratará de as verificar e comunicar à TML. É importante frisar este último ponto: Caso faça edições não triviais no OpenStreetMap (exemplo: colocar a posição a dezenas de paragens como acabou de fazer), é legalmente necessário consentimento explicito seu para a TML tomar posse dos seus dados por intermédio do OpenStreetMap uma vez que a licença atual da TML é incompatível com a do OpenStreetMap.

Caso participe na comunidade Lisboa para Pessoas, é também possível falar diretamente com alguns dos cartógrafos que estão a obter os dados, ainda que sabemos o que temos em falta e eventualmente teremos o levantamento de todos os locais da AML. É uma questão de tempo :)

**Comment by joao-vasconcelos** [comment]
Bom dia @Gasosa12, atualizámos as coordenadas tal como indicado — deverão aparecer no site e nas apps em breve.

Tal como o @claudioap indica, estamos a colaborar com o [Intermodal](https://editor.intermodal.pt/) para corrigir este tipo de situações mais rapidamente e de uma forma massiva. Pretendemos iniciar em breve com o município de Alcochete, seguindo pelos restantes até à conclusão. Este tipo de contribuições é extremamente útil e beneficia todos!

Muito obrigado e keep them coming!

**Comment by Gasosa12** [comment]
Olá @claudioap e @joao-vasconcelos, obrigado pela informação e por corrigirem o erro.
Vou então passar a confirmar primeiro no OpenStreetMap se as paragens estão no local correto antes de reportar este tipo de situações.
Eu quero continuar a ajudar a melhorar o GTFS por isso se eu encontrar mais algum problema ou informação errada eu reporto aqui.
