### ISSUE TITLE
Paragens Danificadas em Queluz

### ISSUE THREAD

**Issue by Gasosa12** [carrismetropolitana/gtfs#119]
**Descreva o erro**  
As paragens `172059` R Heliodoro Salgado 2 e `172495` Queluz (4 Caminhos) tiveram as suas bandeiras arrancadas.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Deve ser informado o operador para proceder à sua reparação.

**Comment by aquint96** [comment]
Boa tarde, antes de mais obrigado, o operador já tem conhecimento do ocorrido e já está a produzir postaletes novos.

**Comment by Gasosa12** [comment]
Vou fechar este issue pois as paragens já foram arranjadas. Obrigado.
