### ISSUE TITLE
[A4] Paragens com duas referencias

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#124]
As referencias 040018 e 040002 são apenas uma paragem pelo que se deve eliminar uma das referencias para que a paragem em questão apenas tenha referencia única.

As referencias 040017 e 040001 são apenas uma paragem pelo que se deve eliminar uma das referencias para que a paragem em questão apenas tenha referencia única.

Em ambas as situações existem postaletes com as duas referencias diferentes.

**Comment by joao-vasconcelos** [comment]
Corrigido com a última atualização. Obrigado!
