### ISSUE TITLE
[A3] Paragem 149002 Estação de Coina em falta

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#125]
Paragem 149002 em falta nas coordenadas 38.584549 -9.050488 da linha 3626 conforme foto abaixo.

![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/7e85e722-6c2d-424b-b317-b17fd66e8a5a)

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98! Muito obrigada pelo alerta. A estação de Coina foi reorganizada e os postaletes já se encontram de acordo com a oferta que se encontra no site.
