### ISSUE TITLE
Linha 2733 – Paragens em falta no GTFS

### ISSUE THREAD

**Issue by Gasosa12** [carrismetropolitana/gtfs#126]
**Descreva o erro**  
Estão em falta as 4 ultimas paragens do percurso da linha 2733 no sentido Moscavide (Metro) -> Loures.
Atualmente o GTFS mostra que o percurso termina na paragem 070473 R Manuel Francisco Soromenho 59 o que não está correto pois o horário em PDF indica que existem mais paragens a seguir até chegar ao terminal correto.

As paragens em falta são por esta ordem:
- 070475 R 4 Outubro (Urmeira)
- 070477 R M Francisco Soromenho 25 (X) Cartório
- 070479 R Manuel Augusto Pacheco 23
- 070032 Lg Marcos Romão Reis Junior (Terminal correto da linha 2733)

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [X] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Screenshots**  

Imagem do mapa do percurso com as paragens em falta assinaladas a verde
![mapaedit](https://github.com/carrismetropolitana/gtfs/assets/132413037/25122fd8-1af1-4b6c-882e-dead4a636895)

Imagem do Website da Carris Metropolitana com o percurso incompleto
![paragens](https://github.com/carrismetropolitana/gtfs/assets/132413037/4094ce23-4a7e-43d1-a696-649504de6e7a)

Imagem do horário em PDF com o percurso correto
![Horarioedit](https://github.com/carrismetropolitana/gtfs/assets/132413037/2bc43411-1005-473d-84d7-aa93a5231764)

**Comment by joao-vasconcelos** [comment]
Olá @Gasosa12, obrigado pelo alerta. Esperamos conseguir resolver em breve!

**Comment by joao-vasconcelos** [comment]
Corrigido com https://github.com/carrismetropolitana/gtfs/commit/d3ae0c64c670cc534e74404e168cb155216215e8
