### ISSUE TITLE
Duplicate route_id present in routes.txt [CarrisMetropolitana.zip]

### ISSUE THREAD

**Issue by sahachandan** [carrismetropolitana/gtfs#127]
There were total 193 **_duplicate route_id_** present in routes.txt under **CarrisMetropolitana.zip**. Kindly fix, thanks.

**Comment by joao-vasconcelos** [comment]
Fixed in https://github.com/carrismetropolitana/gtfs/commit/0e6b8ce77374b1bf7b167396cfb5cb178bd7eb76
Thank you!
