### ISSUE TITLE
[A4] Falta paragem na rota 4417

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#129]
**Descreva o erro**  
Foram adicionadas novas paragens à linha 4417 de acordo com o print abaixo porém falta uma paragem no sentido Setubal (ITS) ao mapa/shape da linha disponível no site. 

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Adicionar 160053 à linha 4417 sentido Setubal (ITS)

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/c21bdabc-77b1-4143-ada6-787b78090911)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/99900736-b227-4b15-b6db-9f78498e7507)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. A linha foi analisada e foram feitas correções.
