### ISSUE TITLE
Verificação de paragens na R. Marquês de Pombal, Bucelas

### ISSUE THREAD

**Issue by joao-vasconcelos** [carrismetropolitana/gtfs#13]
**Descreva o erro**  
Verificação da situação real de paragens na R. Marquês de Pombal e na Pç Tomaz José Machado em Bucelas.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:
- [ ] Área 1 (Viação Alvorada)
- [X] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Screenshots**  
![Screenshot 2023-03-28 at 09 40 40](https://user-images.githubusercontent.com/10943992/228186624-07445b64-bf75-45f1-9d7f-96ec6f13bedb.png)

**Contexto adicional**  
[Google Maps](https://www.google.com/maps/@38.9002512,-9.1181318,121a,35y,342.54h,27.56t/data=!3m1!1e3)

**Comment by joao-vasconcelos** [comment]
Relacionado https://github.com/carrismetropolitana/pdfs/issues/1

**Comment by ScriptForAll** [comment]
Bom dia.
Segue-se de seguida uma imagem com uma numeração das paragens.
![terminais_bucelas](https://user-images.githubusercontent.com/36014883/228203222-1e1084e8-f40d-469b-9b4f-3b0c47170a08.png)

1, 3 e 4 são terminais de partida e 2 e 5 são terminais de chegada.

As paragens 1 e 4 não têm qualquer problema. Partem donde devem partir, os nomes (no caso da 1, quando for corrigido) estão bem e têm os posteletes no local. 

As paragens 2 e 3 são na verdade dentro da Estação e não na Praça Tomaz José Machado (que se localiza bem mais a este que é onde se encontra o jardim). Na verdade, deveriam ter o nome da paragem que aparece como "Bucelas (Est)" mas que no GTFS está "vazia". 
De momento não me recordo, mas creio que nenhuma das paragens têm postelete. No entanto, só na paragem 3 é que seria mesmo necessário colocar para dar as informação das linhas.

No caso da paragem 5, nunca vi um autocarro a parar nela (exceptuando a Boa Viagem, mas muito raramente) pois trata-se mais de uma paragem "técnica" do que uma paragem que acontece no local pois serve apenas para marcar o fim do percurso das rotas. Consoante a chapa a ser feita pelo motorista, um autocarro que venha da R. Marquês de Pombal faz o desembarque ou na paragem 1 ou na 4.

Relativamente aos terminais de partida, de se notar:
- As linhas que partem para Sul (e.g. 2706) partem da paragem 1; 
- As linhas que partem para Oeste (e.g. 2750) partem da paragem 4; 
- As linhas que partem para Este (e.g. 2530) partem da paragem 3.

Edição 2023-04-03: corrigido erro ao afirmar paragem 2 quando queria dizer paragem 3

**Comment by joao-vasconcelos** [comment]
Muito obrigado @ScriptForAll pela resposta hiper-rápida. Assunto resolvido!
