### ISSUE TITLE
[A4] Falta paragem na rota 4433

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#130]
**Descreva o erro**  
Foi adicionada nova paragens à linha 4433 de acordo com o print abaixo porém falta uma paragem no sentido Setúbal (Casal Figueiras) ao mapa/shape da linha disponível no site bem como a remoção de uma paragem que está incorreta. 

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Adicionar 160455 à linha 4433 sentido Setúbal (Casal Figueiras)
Remover paragem 160425

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/05c08f2f-5bbc-476d-81b5-99cbe048c70b)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/5da344f3-a18a-48f1-814b-bddd2605042c)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. Já corrigimos essa situação.
