### ISSUE TITLE
[A4] Ordem de paragens 4451 4452 4453

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#131]
**Descreva o erro**  
A ordem da paragem 160491 nas rotas 4451 4452 4453 não aparenta estar correto em ambos os sentidos obrigando o autocarro a ir atrás no percurso.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Alterar a ordem da paragem 160491 em ambos os sentidos das rotas 4451 4452 4453 como mostra abaixo

**Screenshots**  
Sentido Mitrena (Lisnave)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/8f95706f-6606-4521-bf8d-f1bd2936d12f)
Sentido
Setúbal (ITS)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/2a74074f-500f-4aac-bb5a-efd68a2147b6)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. Esta situação foi analisada e atualmente está tudo correto.
