### ISSUE TITLE
[A4] Shape 4470

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#134]
**Descreva o erro**  
As novas shapes da linha 4470 Setúbal (ITS) - Praia do Creiro via Vila Nogueira de Azeitão foram colocadas nos sentidos trocados, é preciso tambem remover a paragem 160787 no sentido Praia do Creiro via Vila Nogueira de Azeitão que está fora da rota nessa variante e a paragem 

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Trocar as shapes de sentido
Remover a paragem 160787 no sentido Praia do Creiro via Vila Nogueira de Azeitão

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/86f79931-50b1-4507-ab39-245ada69e3aa)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/31477f53-ed20-449f-a3a7-fe8c409ee5c8)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by ricardojorgerm** [comment]
Provavelmente basta trocar os shape_id do trips.txt se elas estao corretas mas trocadas de sentido.

**Comment by DiogoBaptista98** [comment]
@joao-vasconcelos penso que a situação já se encontre resolvida pelo que encerro o issue.
