### ISSUE TITLE
[A4] Falta paragens 4503

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#135]
**Descreva o erro**  
alteração / ajuste
Duas paragens em falta na linha 4503

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Adicionar paragem 100055 sentido Atalaia
Adicionar paragem 100058 sentido Montijo

**Screenshots**  
Sentido Atalaia 100055
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/b47ee4c2-d2e8-4971-b6cb-947c31ce74e7)
Sentido Montijo 100058
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/7f6fa9b2-fef8-4590-9507-bd9cba5230d9)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. A situação já se encontra resolvida.
