### ISSUE TITLE
[A4] Serviço linha 4471

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#136]
**Descreva o erro**  
A linha 4471 tem pouca dimensão pelo que o tipo de serviço deveria ser alterado de longa para próxima

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
4471 linha proxima

**Screenshots**  
linha 4471
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/a773b658-393e-4f94-8298-ba112411110d)

linha semelhante que é próxima
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/f85960fb-3ed2-4558-a347-9083491172bf)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Olá @DiogoBaptista98, para já vai ser mantido assim. Obrigado!
