### ISSUE TITLE
Linha 4612 – Paragens trocadas e localização errada

### ISSUE THREAD

**Issue by Gasosa12** [carrismetropolitana/gtfs#139]
**Descreva o erro**  
As paragens 130687 e 130688 ambas com o nome R 25 Abril X R Das Fazendas têm as suas localizações ligeiramente erradas no GTFS causando um erro no percurso da linha 4612.

Imagem do mapa com as paragens. 
A vermelho a localização atual e errada, a verde a localização correta.
![InkedBmar](https://github.com/carrismetropolitana/gtfs/assets/132413037/fa166c9a-642c-4cfd-8bb6-6dde3964967b)

Depois de corrigidas as localizações das paragens devem ser corrigidos os sentidos da linha 4612. 

No sentido Palmela (Terminal) a linha serve a paragem 130688 e não a paragem 130687.
![InkedInkedSPalm](https://github.com/carrismetropolitana/gtfs/assets/132413037/c8190b2e-4677-48a2-b5c5-6d6f30fad32c)

No sentido Bairro dos Marinheiros a linha serve a paragem 130687 e não a paragem 130688.
![InkedSBmar](https://github.com/carrismetropolitana/gtfs/assets/132413037/2a9d0244-58c4-4c5a-acdd-38d12624fd9c)

**Contexto adicional**  
Não é necessário fazer alterações no terreno pois as paragens já se encontram nas localizações corretas.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Comment by joao-vasconcelos** [comment]
[falta corrigir o percurso, que tem associadas as paragens do sentido inverso]

**Comment by inesclemente** [comment]
Olá @Gasosa12, obrigada pelo alerta. A situação já se encontra corrigida e visivel no site.
