### ISSUE TITLE
Linha 4610 – Paragem em falta

### ISSUE THREAD

**Issue by Gasosa12** [carrismetropolitana/gtfs#140]
**Descreva o erro**  
Está em falta a ultima paragem do percurso da linha 4610 no sentido Barreiro (Terminal) -> Bairro dos Marinheiros.

Atualmente o GTFS mostra que o percurso no sentido Bº Marinheiros termina na paragem 130686 Bº ALENTEJANO (R 25 ABRIL 13) o que deve estar errado visto que no sentido Barreiro (Terminal) a primeira paragem do percurso é a paragem 130714 Bº ALENTEJANO (R PESSEGUEIROS) devendo ser esta a paragem terminal também no sentido Bº Marinheiros.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Adicionar a paragem 130714 Bº ALENTEJANO (R PESSEGUEIROS) ao percurso no sentido Bº Marinheiros.

**Contexto adicional**  
O shape do percurso em ambos os sentidos também parece estar errado na zona envolvente às paragens mencionadas.

**Screenshots**  
![Inked4610](https://github.com/carrismetropolitana/gtfs/assets/132413037/9010217e-65e8-4b17-9077-70261079b509)

**Comment by inesclemente** [comment]
Olá @Gasosa12, obrigada pelo alerta. A situação já foi analisada e corrigida, em breve ficará disponível.
