### ISSUE TITLE
A2 - Conflito de IDs da paragem 111021

### ISSUE THREAD

**Issue by ricardojorgerm** [carrismetropolitana/gtfs#141]
**Descreva o erro**  
A paragem com o codigo 111021 no GTFS da Area 2:

`111021,111021,"111021","R Flor Minho (X) R Egas Moniz","","",38.809725,-9.215175,,,,,,,,,,,,,,,,,,,,,,,PT170,1116,,`

Não é equivalente à do mesmo código na referencia gtfs-common-files como outra paragem importada da Área 1:

`111021,R Pinhal Castelo Vide (X) R Aqueduto,38.815408,-9.235176,1,0,0,0,,,0,,,111021,,1,,,,PT170,11,1116,,Odivelas,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,,,`

A paragem `R Flor Minho (X) R Egas Moniz` não se encontra representada no gtfs-common-files. Foi feita uma procura pelo nome similar sem resultados, e uma procura com outro nome e com coordenadas similares, sem resultados.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [x] Área 1 (Viação Alvorada) 
- [x] Área 2 (Rodoviária de Lisboa) <- paragem em falta
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Proposta de resolução**  

- Gerar um novo identificador para `R Flor Minho (X) R Egas Moniz` que não colida com o existente na área 1 para uma paragem diferente.
- Referenciar o identificador no gtfs-common-files para a nova paragem.
- Contactar a área 2 e indicar o novo identificador de `R Flor Minho (X) R Egas Moniz`

**Comment by ricardojorgerm** [comment]
Isto continua a ser um problema entre as bases de dados comuns e da A2:

111021,111021,"111021","R Flor Minho (X) R Egas Moniz","","",38.809725,-9.215175,,,,,,,,,,,,,,,,,,,,,,,PT170,1116,,

Obrigado!

**Comment by joao-vasconcelos** [comment]
`111021` -> `111030`
