### ISSUE TITLE
A4 - Espinha de 4604 dir. Barreiro com paragem fora do circuito

### ISSUE THREAD

**Issue by ricardojorgerm** [carrismetropolitana/gtfs#142]
**Descreva o erro**  
A paragem EM 533-1 ROTUNDA URB CARVALHINHO na espinha da 4604 dir. Barreiro não faz sentido no percurso indicado

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Tentei encontrar IDs duplicados ou trocados, mas não encontrei. Parece que ou está a mais, ou há outra paragem que foi perdida no processo de informatização.

**Screenshots**  
<img width="1394" alt="Screenshot 2023-06-03 at 13 16 31" src="https://github.com/carrismetropolitana/gtfs/assets/4206285/14702f6c-1f3f-4672-8624-c7b7de8cd3df">

**Comment by joao-vasconcelos** [comment]
Corrigido. Obrigado!
