### ISSUE TITLE
A4 - Barreiro - Paragens duplicadas (040018 duplicado de 040002) e (040017 duplicado de 040001)

### ISSUE THREAD

**Issue by ricardojorgerm** [carrismetropolitana/gtfs#144]
**Descreva o erro**  
Existem duas paragens duplicadas na A4 Barreiro:

- A paragem 040017 é duplicada de 040001
- A paragem 040018 é duplicada de 040002

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, apenas um ID de paragem pois estão colocalizadas fisicamente.

**Comment by DiogoBaptista98** [comment]
Deve-se evitar a duplicação de issues, esta é uma copia de uma anterior já existente. https://github.com/carrismetropolitana/gtfs/issues/124

**Comment by ricardojorgerm** [comment]
Duplicado de #124
