### ISSUE TITLE
[A2] Paragem 070577 a desativar

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#151]
**Descreva o erro**  
A paragem 070577 que apenas contem a linha 2029 está extremamente próxima (90m) da 070575 que também contem a mesma linha pelo que não faz sentido a existência das duas, pede-se que por isso seja desativada a paragem 070577 sendo que a 070575 se mantém por conter todas as outras linhas.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [X] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Desativar a paragem 070577

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/2a5dcfec-9d4f-4290-9234-4123a19d098f)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by LaPingvino** [comment]
Veja bem que o sentido aqui é 1° de Maio ser terminal desta linha, já que na paragem ao metro não pode ficar parado na espera da rodada seguinte.
