### ISSUE TITLE
Correcção Campo Grande

### ISSUE THREAD

**Issue by claudioap** [carrismetropolitana/gtfs#152]
**Descreva o erro**  
O Terminal 1 do Campo Grande necessita de ser ajustado à realidade no GTFS.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [x] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
A seguinte imagem descreve a realidade do teminal do Campo Grande:
![Campo Grande](https://github.com/carrismetropolitana/gtfs/assets/5624169/d5f77c1d-82f9-459f-aa65-a71a95b557d6)

Já a seguinte imagem descreve a situação actual (pontos laranja são o GTFS actual, pontos azuis são paragens reais):
![image](https://github.com/carrismetropolitana/gtfs/assets/5624169/0e0d629f-8fac-4120-ada7-d105139728e0)

**Contexto adicional**  

Paragens duplicadas:
- A 060337 aparece fisicamente em dois terminais (T24 e T26)

Paragens que não tem representação física:
- 060156 (duplicação da 060155, tem rotas inadvertidamente)
- 060369 (duplicação da 060337, tem rotas inadvertidamente, a 2842 deve de ser movida para a 060337)

Rotas atribuídas indevidamente:
- A 2842 deve de ser movida da 060369 para a 060337

Problemas adicionais:
- Não existe uma paragem de desembarque por baixo da inversão da Av. General Norton de Matos apesar de esse local (juntamente com a paragem da 061200) efetuar desembarques.

Esta informação encontra-se mais sintetizada no ficheiro excel que foi partilhado pelo @DiogoBaptista98 , podendo o mesmo ser utilizado para confirmação. Será ainda partilhado (em privado devido à afluência de passageiros) um video que valida os factos apresentados.

**Comment by joao-vasconcelos** [comment]
Fixed by https://github.com/carrismetropolitana/gtfs/commit/0d25c5d57aa2a91562cacbb4ea8b3adb65fabc08

**Comment by LaPingvino** [comment]
isto vai ajudar muitíssimo, Campo Grande sem isto é um pesadelo.
