### ISSUE TITLE
[A4] Paragens em falta

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#153]
**Descreva o erro**  
Faltam as seguintes paragens ao GTFS

160821 Figueirinha (Casamata)
160822 Figueirinha (Casamata)
160335 Comenda (Parque Merendas)
160336 Comenda (Parque Merendas)
160337 EN 379-1 X Qta Casal Ajuda
160338 EN 379-1 X Qta Casal Ajuda
160339 EN 379-1 X (Qta Maria Esguelha)
160340 EN 379-1 X (Qta Maria Esguelha)

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Adicionar 
38.486322,-8.940396 160821 Figueirinha (Casamata) - 4474 4476
38.486338,-8.940121 160822 Figueirinha (Casamata) - 4474 4476

38.508034,-8.929226 160335 Comenda (Parque Merendas) - 4414 4415 4474
38.507899,-8.928798 160336 Comenda (Parque Merendas) - 4414 4415 4474
38.510680,-8.923134 160337 EN 379-1 X Qta Casal Ajuda - 4414 4415 4474
38.510734,-8.923205 160338 EN 379-1 X Qta Casal Ajuda - 4414 4415 4474
38.512353,-8.918599 160339 EN 379-1 X (Qta Maria Esguelha) - 4414 4415 4474
38.512281,-8.918563 160340 EN 379-1 X (Qta Maria Esguelha) - 4414 4415 4474

**Screenshots**  
Exemplo: um dos postaletes encontrados
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/b8a51b82-4faa-4bb2-8f14-7074f8a7a940)

**Contexto adicional**  
Importante adicionar as linhas a estas paragens visto que estão descritas em postalete.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. A situação já foi corrigida e em breve ficará disponível.
