### ISSUE TITLE
[A4] Paragens em falta

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#154]
**Descreva o erro**  
Antiga paragem TST que está  desativada mas onde colocaram um PIP, não tem postalete nem está no GTFS

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Nova paragem nas coordenadas 38.703502,-8.952891

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/f886a601-6875-4d73-9caa-5f04fe7e2ca5)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/3e0aeb6e-04ab-4368-8392-3820c5ba1e0c)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
A paragem foi criada e tem o código `100038`. Obrigado!
