### ISSUE TITLE
Rodoviária de Lisboa .gtfs data issue

### ISSUE THREAD

**Issue by mamedebarreiros** [carrismetropolitana/gtfs#155]
**Descreva o erro**  
When trying to use the gtfs data from Rodoviária de Lisboa, it seems that there is an issue with the UTF-8 format, not allowing us to use properly the data.
Can you please have a look and try to correct the issue?

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 2 (Rodoviária de Lisboa)

Kind regards

Mamede Barreiros

**Comment by ricardojorgerm** [comment]
Hello,

I'm an independent developer, not afiliated with Carris Metropolitana. However, I don't understand your report as currently data consumers are not using operator-specific GTFS files.

The current GTFS in usage is a combined GTFS for all areas of Carris Metropolitana, named "**CarrisMetropolitana.zip**". The per area GTFS files are mostly for backward compatibility with consumers that onboarded the GTFS file at an earlier stage. If you have prior files from Rodoviária de Lisboa from other sources or from prior to the migration to Carris Metropolitana, these are no longer supported.

- Are you reporting issues in the main **CarrisMetropolitana.zip** GTFS file?
- The GTFS file is updated up to several times per week. Are those issues happening in the latest committed version? Do you know the commit hash or the exact timestamp of the file you downloaded?
- Can you say specifically what file, line and what character is causing you issues with parsing the file? 
- Do you have a log output you can provide from your data consumer software?

**Comment by joao-vasconcelos** [comment]
Hello @mamedebarreiros, the area-specific GTFS files may not have the latest network information. It is strongly recommended to use CarrisMetropolitana.zip for all analyses. Regardless, we have updated today with new files. If you'd like you can test again. Thank you!

Also, thank you @ricardojorgerm for the quick response.

**Comment by mamedebarreiros** [comment]
Hello @joao-vasconcelos,
Many thanks for feedback and support. Appreciated from our side and my technical colleagues are already using properly the data available.

Also thanks to @ricardojorgerm for the feedback and support.
kind regards
