### ISSUE TITLE
[A1] nome da linha 1111, 1121 e 1125

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#156]
**Descreva o erro**  
As linhas 1111, 1121 e 1125 apresentam-se no nome como circular mas os seus percursos não são circular.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Mudança dos nomes da linhas retirando a referencia errada a circular

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/ce8173c0-e906-4e3a-8cac-f709d12f1379)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by Gasosa12** [comment]
As linhas 1111 e 1121 também se apresentam com o nome circular mas na realidade não são, por isso se possível devem ser corrigidos os nomes destas linhas também.

**Comment by DiogoBaptista98** [comment]
> As linhas 1111 e 1121 também se apresentam com o nome circular mas na realidade não são, por isso se possível devem ser corrigidos os nomes destas linhas também.

Bem visto! O issue foi assim actualizado! Cumprimentos

**Comment by aquint96** [comment]
Boa tarde, informo que estas alterações já foram realizadas.
Obrigado.
