### ISSUE TITLE
[A2] Paragem em falta Hospital Beatriz Ângelo (Consultas) 

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#158]
**Descreva o erro**  
No Hospital Beatriz Ângelo (Consultas) devem existir 2 paragens e não apenas uma, por isso falta uma paragem no GTFS que sugiro ser a 070368 Hospital Beatriz Ângelo (Consultas) 

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [X] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Mover
070369 Hospital Beatriz Ângelo (Consultas) 38.822059,-9.176627
Adicionar
(070368) Hospital Beatriz Ângelo (Consultas) 38.822280,-9.176138

Colocar as rotas em cada uma das sops de acordo com a informação em screenshot abaixo

**Screenshots**  
Paragem a vermelho existente (a mover), a azul em falta (a criar)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/4481e071-d13a-4750-ab12-f2dba81783db)

Paragem em falta
(070368) Hospital Beatriz Ângelo (Consultas)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/fed9326a-ff16-45a4-a9ac-1a52335f84ec)

Paragem existente
070369 Hospital Beatriz Ângelo (Consultas)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/2b758606-4fa7-4062-959f-9225c14c17f0)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. A situação já se encontra corrigida e visível no site.
