### ISSUE TITLE
[A1] 1704_3_1 shape associada p0_108 com erros

### ISSUE THREAD

**Issue by ricardojorgerm** [carrismetropolitana/gtfs#159]
**Descreva o erro**  
A shape p0_108 associada a 1704_3 possui uma volta desnecessaria de saida-reentrada no acesso autoestrada A5 e uma saida do Marques de Pombal incorreta. 

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [x] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Circulação pela saída sul do Marques de Pombal e procedencia via autoestrada **sem** saída e **sem** inversao de marcha na avenida engenheiro duarte pacheco. 

**Screenshots**  
https://www.carrismetropolitana.pt/horarios/?date=2023-06-26&municipality_id=&route_short_name=1704&route_id=1704_3&direction_id=1&trip_id=p0_1704_3_2_0700_0729_0_1&stop_id=060033&stop_sequence=1

<img width="802" alt="image" src="https://github.com/carrismetropolitana/gtfs/assets/4206285/46b40707-9027-4224-b5da-c96e1e9280d3">

Saída errada da interface (ver shapes das variantes para referencia)
<img width="639" alt="image" src="https://github.com/carrismetropolitana/gtfs/assets/4206285/a32405cb-4b4a-4706-9825-b77e6369dc09">

Inversão de marcha dupla na A5, voltando a Lisboa na Av. Eng. Duarte Pacheco e reentrando na A5 
<img width="442" alt="image" src="https://github.com/carrismetropolitana/gtfs/assets/4206285/cc9670d8-823b-4ca1-896e-6d35b3e9beba">

**Comment by aquint96** [comment]
Informamos que a Shape já foi corrigida, obrigado pela informação.

**Comment by ricardojorgerm** [comment]
Grato pela ajuda @aquint96, endereço-lhe os meus melhores cumprimentos e votos de um excelente final de Agosto.
