### ISSUE TITLE
Erro de localização da paragem no Google Maps - StopId 060236

### ISSUE THREAD

**Issue by pedrolcfonseca** [carrismetropolitana/gtfs#16]
**Descreva o erro**  
ID de paragem 060236 no local errado 

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [X] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
A paragem R Melo Antunes fica mais a norte da localização que está no Google Maps.
Coordenadas de onde está presentemente: 38.777700523718295, -9.145834117250208
Coordenadas de onde deveria estar: 38.77917641198868, -9.14458588076392

**Screenshots**  
![060236 (R  Melo Antunes)](https://user-images.githubusercontent.com/129157973/228489616-c7077db2-3a3f-4976-8e40-a4bed9aa275e.jpg)

**Comment by joao-vasconcelos** [comment]
Fixed! Obrigado @pedrolcfonseca
