### ISSUE TITLE
Linhas inexistentes em routes.txt referenciadas em fare_rules.txt

### ISSUE THREAD

**Issue by joaodcp** [carrismetropolitana/gtfs#161]
**Descreva o erro**  
Algumas linhas são referenciadas no ficheiro fare_rules.txt, sendo que não existem no ficheiro routes.txt

**Valor(es) esperado(s)**  
As linhas inexistentes no ficheiro routes.txt não devem ser referenciadas no ficheiro fare_routes.txt, já que isto constitui um erro na maior parte dos parsers e validadores de GTFS.

**Contexto adicional**  
Após erro na aplicação que consome o vosso GTFS, verifiquei se a situação se repetia para mais linhas.
URL do relatório: https://gtfs-validator-results.mobilitydata.org/ffaa6d26-e5e3-48a5-b7dd-a22a3bec5991/report.html

As linhas são: 3002_0, 3004_1, 3016_0, 3031_0, 3022_1, 3032_0, 3219_0, 3219_1, 3034_1, 3625_0, 3005_0, 3626_2, 3020_0, 3028_0, 3703_2, 3029_0, 3710_1, 3037_0

**Comment by joao-vasconcelos** [comment]
Olá @joaodcp, obrigado pelo aviso. Corrigido na última versão. Houve alteração de route_ids na A3 (algumas rotas _1, _2 passaram a _0, outras são novas).
