### ISSUE TITLE
[A2] Erros nos horários da 2762

### ISSUE THREAD

**Issue by ScriptForAll** [carrismetropolitana/gtfs#162]
**Descreva o erro**  
Os horários da linha 2762 apresentados no site e os respetivos pdf diferem.
No sentido Campo Grande -> Bucelas, os horários que aparecem no site têm horas diferentes das dos que aparecem no pdf.
No sentido Bucelas -> Campo Grande, o pdf da paragem inicial (070135) está trocado por um pdf da paragem "Ribas Baixo (Esc)" (0715780). De se notar que esta paragem não tem um pdf associado no site. 

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [x] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

1. Corrigir os horários no sentido CG -> Bucelas
2. Regularizar os pdfs trocados mencionados

**Screenshots**  
Se fizer sentido, adicione imagens que ajudem a explicar o problema.
Sentido Campo Grande -> Bucelas
![Screenshot_20230628_193504](https://github.com/carrismetropolitana/gtfs/assets/36014883/81933c3f-d59e-4808-b8cc-1b9b4ac88f6b)
![Screenshot_20230628_193539](https://github.com/carrismetropolitana/gtfs/assets/36014883/aeea840e-e9b3-4b02-a0a6-aabb33422106)

Sentido Bucelas -> Campo Grande
![Screenshot_20230628_192730](https://github.com/carrismetropolitana/gtfs/assets/36014883/4bfaa5f4-c3ef-4e5d-9c17-b1acbebcec21)
![Screenshot_20230628_192814](https://github.com/carrismetropolitana/gtfs/assets/36014883/827cc6df-6d56-46a3-ae1e-4b845593cfe0)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Olá @ScriptForAll, obrigado pelo alerta e lamento a demora na reposta. Estamos a reformular o sistema de geração de PDFs. De qualquer forma, os horários estão sempre disponíveis no site e com tempo real — https://beta.carrismetropolitana.pt/lines/2762
