### ISSUE TITLE
[A1] Postaletes danificados

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#163]
**Descreva o erro**  
As seguintes paragens tem a placa do postalete arrancada:
050009
050462 - falta também horário
050463
050518
120895

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Recolocação da placa no postalete

**Screenshots**  
Se fizer sentido, adicione imagens que ajudem a explicar o problema.

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by aquint96** [comment]
tratado
