### ISSUE TITLE
[A3] Paragens da linha 3522

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#165]
**Descreva o erro**  
A linha sazonal de verão 3522 foi colocada novamente em serviço mas as paragens da mesma não foram atualizadas de acordo com a realidade atual.

4 paragens foram recentemente desativadas sendo por isso o esquema de circulação daquela zona diferente.
140263 140266 140281 140265

![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/a0125cc6-8c65-4777-a0be-17435fb6b54f)

A linha deve por isso ir pela Rua Teófilo Braga de acordo com as restantes, aqui um esquema da 3111 exemplificando o esquema de circulação naquela zona.

![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/2fe3c636-dde2-4e76-a75b-7ba91b0611b5)

Paragem 140203 não existe

![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/943b65c8-07de-494d-aff2-2aa8a8bbff55)

Paragem 140682 e 140681 (uma em cada sentido( está em falta (por questão de uniformização, a 3521 e a 3523 fazem paragem em ambas)

![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/2856a141-2d73-44e1-99f6-7194cde9825e)

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [X] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Eliminar paragem 140203
Adicionar 140682 e 140681 
Atualizar a linha em Paio Pires removendo as paragens desativadas 140263 140266 140281 140265

**Screenshots**  
Acima adicionados

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. A situação já se encontra corrigida e disponível no site.
