### ISSUE TITLE
[A3] Erro ortográfico linha 3223

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#166]
**Descreva o erro**  
Erro ortográfico, deve der MOAGEM e não MOGEM

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [X] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Correcção ortográfica

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/eee3b495-a537-47f2-ac99-2b10624a8801)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. A situação já se encontra resolvida e disponível no site.
