### ISSUE TITLE
[A1] Nova pagarem linha 1253

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#168]
**Descreva o erro**  
Recentemente foi adicionada a paragem 171926 à linha 1253 seguido antigas paragens da 433 que ali existiam, sugiro também que seja adicionada a paragem Fonte da Sabuga que ficou por colocar.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Criar nova paragem Fonte da Sabuga 38.7954978 -9.387292

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/d4b88641-2fbe-4ae9-9eff-383fd0753476)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/2761431f-8b4c-4e79-9be2-acc5887f4f35)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. Neste momento não vai ser possivel fazer essa alteração.
