### ISSUE TITLE
[A4] Falta paragem na espinha 4643

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#169]
**Descreva o erro**  
Falta a ultima paragem Sesimbra (Terminal) na espinha 4643

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/5dbf92ca-747a-448f-b0ed-5750f83237fb)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. Já corrigimos o erro, entretanto ficará disponível no site.
