### ISSUE TITLE
[A4] Remoção paragem 4515

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#170]
**Descreva o erro**  
Com a entrada em funcionamento da paragem 100038 foram atualizadas as linhas que passavam nessa paragem sendo mudadas para nova 100331 porem foi esquecida a linha 4515.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Remover paragem 100331 da linha 4515

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/eac8de6e-fde0-45a4-9b10-e31b8052ecf0)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. Já analisamos a situação e em breve ficaram disponíveis as alterações.
