### ISSUE TITLE
[A4] Paragem em falta 4514

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#171]
**Descreva o erro**  
Falta a paragem 100038 na linha 4514 sentido Canha

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Adicionar paragem 100038 à linha 4514 sentido Canha

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/dcc62b74-a159-47ef-8003-5fed5730f55e)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. A situação já foi corrigida, em breve ficará disponivel.
