### ISSUE TITLE
[A3] Trajeto da linha 3625 não conta com desvio pelas obras da rotunda

### ISSUE THREAD

**Issue by LaPingvino** [carrismetropolitana/gtfs#172]
**Descreva o erro**  
O caminho descrito é o plano original. Veja desvio como aplicado à linha 3601

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [x] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
O caminho passa pela rua ao lado da rotunda na avenida Bocage como o 3601 faz

**Screenshots**  
Caminho "errado" (até a rotunda completar):
![Screenshot_2023-07-02-04-36-47-826_com.android.chrome.jpg](https://github.com/carrismetropolitana/gtfs/assets/10294/7605f751-51d1-434c-86d6-7d849d78eced)
Caminho da linha 3601 contando com o desvio:
![Screenshot_2023-07-02-04-37-40-300_com.android.chrome.jpg](https://github.com/carrismetropolitana/gtfs/assets/10294/502ca08c-9a92-4910-afac-e98d2923eeb5)

**Contexto adicional**  
Desvio é temporário mas tanto que eu saiba por toda temporada estival.

**Comment by LaPingvino** [comment]
Vi agora que já foi mencionado em #167 (mas sem mencionar a razão do mesmo)

**Comment by DiogoBaptista98** [comment]
> Vi agora que já foi mencionado em #167 (mas sem mencionar a razão do mesmo)

O issue é duplicado deste https://github.com/carrismetropolitana/gtfs/issues/167 pelo que seriam melhor fechar o mesmo para não haver repetições desnecessárias, cumprimentos.
