### ISSUE TITLE
[A4] Linha Mar 4643 - 45mins entre paragens proximas  (stop_times.txt)

### ISSUE THREAD

**Issue by ricardojorgerm** [carrismetropolitana/gtfs#173]
**Descreva o erro**  

Na linha `4643_0` direção Sesimbra (Terminal) (directionId=0), 
em todas as trips:

```
p3_4643_0_1|1100|0830
p3_4643_0_1|1100|1415 
```

Note que existe uma duração de 45 mins improvável entre as seguintes paragens de distância próxima:

```
14:32 AFONSOEIRO (AV PEDRO NUNES 968) - 100041

15:17 MONTIJO (AV PORTAS DA CIDADE) - 100423
```

<img width="886" alt="image" src="https://github.com/carrismetropolitana/gtfs/assets/4206285/3690b2f0-fb87-453a-99aa-c274ad1621f6">

<img width="885" alt="image" src="https://github.com/carrismetropolitana/gtfs/assets/4206285/3e39b1c3-b62b-4d80-b95d-9fa66bbe3f19">

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  

No sentido oposto, o percurso entre as duas paragens indicadas do lado da rua correspondente é de 1 min, pelo que esta será a melhor estimativa do valor correto.

**Comment by ricardojorgerm** [comment]
Note também o erro no contorno da shape - é possivel que o operador em questão não tenha tomado cuidado no sentido da rua certo e tenha gerado estes valores discrepantes ao estimar o tempo de percurso

**Comment by ricardojorgerm** [comment]
Noto tambem outro erro nas paragens longe uma da outra:

```
15:17 MONTIJO (AV PORTAS DA CIDADE)

15:19 QTA CONDE (EN10) PARQUE VILA
```

Estas sim deveriam demorar mais tempo, mas parece que demoram apenas 2 minutos, o que é improvavel.

Isto sugere que a autoridade/operador tentou adicionar ou remover paragens, e colocou fora de ordem a travessia entre montijo e quinta do conde, tendo-a colocado entre duas paragens no montijo.

**Comment by joao-vasconcelos** [comment]
Olá @ricardojorgerm, em princípio deverá estar melhor ajustado no site. Obrigado!
