### ISSUE TITLE
[A2] 2734_0_0 paragem a mais na espinha

### ISSUE THREAD

**Issue by ricardojorgerm** [carrismetropolitana/gtfs#174]
**Descreva o erro**  
A espinha sentido Sacavém contem a paragem

`Lisboa (Areeiro) Av Joao XXI 56 #061214`

em erro.

Vide:
<img width="1434" alt="Screenshot 2023-07-02 at 18 03 30" src="https://github.com/carrismetropolitana/gtfs/assets/4206285/96bc0583-3af5-4880-955b-794b1d03e439">

https://www.carrismetropolitana.pt/horarios/?route_short_name=2734&date=2023-07-02&municipality_id=&route_id=2734_0&direction_id=0&trip_id=p1_2734_0_1%7C3%7C3%7C1855&stop_id=061214&stop_sequence=11

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [x] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Sem a paragem a mais na espinha

**Comment by ricardojorgerm** [comment]
Isto é devido ao conflito na base de dados de paragens na área 2, que contém:

061214,61214,"061214","Olivais Norte","","",38.775895,-9.111052,,,,,,,,,,,,,,,,,,,,,,,PT170,1106,,

para o código de paragem que está atualmente atribuido para a paragem do Areeiro.

**Comment by joao-vasconcelos** [comment]
`061214` -> `060336`

**Comment by joao-vasconcelos** [comment]
https://github.com/carrismetropolitana/gtfs/commit/19368f2af79998316604c837b9a2ef935c2911a9
