### ISSUE TITLE
Pedido Esclarecimento ficheiros GTFS A2 de 2023/06/30

### ISSUE THREAD

**Issue by edgarzeferino** [carrismetropolitana/gtfs#175]
Bom dia,

**Descrição**  
No dia 2023/06/28 colocaram o ficheiro [CM_GTFS_A2.zip] atualizado. O ficheiro stop_times.txt possui 1285629 linhas, incluindo cabeçalho.
No dia 2023/06/30 atualizaram novamente este ficheiro com a descrição "[atualização embarque/desembarque A1, A2 e A4]". O ficheiro stop_times.txt só possui 390009 linhas, incluindo cabeçalho. 
Esta versão (2023/06/30) não é completa. Correto? Podem indicar-me o que muda, mais detalhadamente? Atualizaram apenas algumas colunas ou registos inteiros? Se forem apenas colunas, quais mudaram?

Justificação:
Eu tenho um processo de tratamento de ficheiros que esmaga o anterior, substituindo-o. Com estes dados mais reduzidos, não posso substituir mas não sei o que mudar...
Obrigado

**Área(s) afetada(s)**  
A sugestão é relativa a que áreas?

- [ ] Área 1 (Viação Alvorada)
- [ X] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Comment by joao-vasconcelos** [comment]
Bom dia @edgarzeferino, os ficheiros individuais não deverão ser utilizados para consulta direta. O arquivo unificado CarrisMetropolitana.zip contém simplificações e ajustes para garantir a validade do feed.

A situação que refere deve-se a ter sido utilizado o plano mensal da Área 2, em vez do plano anual. Este plano mensal tem apenas a operação para o mês de Julho. Por várias razões teremos de utilizar o mensal ou o anual, mas garantimos sempre que para o mês atual existe uma versão atualizada da operação no ficheiro consolidado CarrisMetropolitana.zip.

Obrigado!
