### ISSUE TITLE
[A1] 050395 Postalete danificado

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#176]
**Descreva o erro**  
Paragem 050395 sem postalete

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Recolocação do postalete

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/4d809bb2-c210-4381-b014-7fa805a6a619)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by aquint96** [comment]
Boa tarde, temos indicação que o Postalete já se encontra no local.
Obrigado.
