### ISSUE TITLE
[A3] Paragens 140239 e 140240

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#177]
**Descreva o erro**  
Estas 2 paragens não existem no terreno, faziam todo o sentido existirem, aguarda-se que sejam colocadas ou os pontos serão removidos no GTFS?

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [X] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Remover 140239 e 140240 ou colocar postalete

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/0a721364-dc19-46b1-a9a8-0f248d532f9f)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. Entretanto esta situação já foi corrigida e as paragens foram removidas do GTFS.
