### ISSUE TITLE
[A4] 100445 010157 e 010158 Paragem sem poste

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#179]
**Descreva o erro**  
As paragens 100445 010157 e 010158 não tem qualquer referencia da sua existência no terreno pelo que se pede a colocação dos postaletes.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
Paragens 010157 e 010158
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/2fae7b09-1f81-431f-a72a-ba900a21019c)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/ef36bdbd-17e2-43dc-b30a-09f090bdfbc1)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. A situação já se encontra resolvida no terreno.
