### ISSUE TITLE
[A4] Terminal de Rio Frio

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#180]
**Descreva o erro**  
As paragens a vermelho 130505 e 130506 não existem, ou são colocadas ou são removidas, o terminal está a ser feito na paragem roxa 130436 que tambem não tem postalete devido de [Desembarque], a primeira paragem de onde partem as linhas é a verde 130435 onde se encontra o único postalete.
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/af45bfe6-93f2-4aa7-b036-014fe8518aca)

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Resolução do terminal de Rio Frio, neste momento a única paragem que tem correspondência com os dados em GTFS é a 130435 sendo que as outras não tem qualquer referencia física no terreno.

**Screenshots**  
Se fizer sentido, adicione imagens que ajudem a explicar o problema.

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Corrigido. Deverão ter sido colocados postes e postaletes nas paragens mencionadas, e eliminada a paragem 130506. Obrigado!
