### ISSUE TITLE
[A3] 3005 Erro shape e falta de stop

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#188]
**Descreva o erro**  
A linha 3005 tem erro na shape e falta associar a paragem 20201 duas vezes como abaixo identificado

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [X] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Correção da shape
Adicionar stop 20201 x2

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/32ae29e6-86bc-49b7-955a-1b80e463a40b)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/3f302a8e-7df9-4a8f-8801-fa681f05c7ed)
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/947c6055-946c-44c7-b2a9-2756840feeab)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. A situação já se encontra resolvida e disponível no site.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. A situação já se encontra resolvida e disponível no site.
