### ISSUE TITLE
Não há "calendar" na Carris Metropolitana, só "calendar_date". É propositado?

### ISSUE THREAD

**Issue by ruicolacopt** [carrismetropolitana/gtfs#189]
**Descreva o erro**  
Uma explicação clara e concisa sobre o erro identificado.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [x] Área 1 (Viação Alvorada)
- [x] Área 2 (Rodoviária de Lisboa)
- [x] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
Se fizer sentido, adicione imagens que ajudem a explicar o problema.

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Olá @ruicolacopt, sim é propositado. A utilização do calendar_dates.txt permite-nos uma maior flexibilidade no ajuste dos calendários para a situação atual da AML. É um modelo de utilização permitido pelo standard. Obrigado!

**Comment by ruicolacopt** [comment]
É verdade, João, e já consegui que funcionasse bem, o erro era meu. Obrigado!
