### ISSUE TITLE
2790 - Erro na sequência de paragens num dos sentidos + correção de coordenadas

### ISSUE THREAD

**Issue by joao-vasconcelos** [carrismetropolitana/gtfs#19]
**Descreva o erro**  
Ambos os sentidos da base têm a mesma paragem, um deles está errado.
https://www.carrismetropolitana.pt/horarios/?route_short_name=2790&date=2023-03-31&municipality_id=&route_id=2790_0&direction_id=0&trip_id=p1_2790_0_2%7C1%7C2%7C0915&stop_id=071641&stop_sequence=20

Paragens p/ verificação de coordenadas:
071639 | En 10 (X) Estação Bobadela | 38.807700 | -9.095520
071641 | En 10 (X) Estação Bobadela | 38.808800 | -9.095020

Maps:
https://www.google.com/maps/place/En+10+(X)+Esta%C3%A7%C3%A3o+Bobadela/@38.8077744,-9.0954299,179a,35y,314.49h,0.28t/data=!3m1!1e3!4m6!3m5!1s0xd192e05d4bca35d:0xb83beaa4b3a6bd46!8m2!3d38.8077!4d-9.09552!16s%2Fg%2F11shqf7jxt

**Área(s) afetada(s)**  
- [ ] Área 1 (Viação Alvorada)
- [X] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Comment by DiogoBaptista98** [comment]
A linha base 2790 no sentido Areeiro não está disponível sendo uma duplicação do sentido inverso. 

> **Descreva o erro** Ambos os sentidos da base têm a mesma paragem, um deles está errado. https://www.carrismetropolitana.pt/horarios/?route_short_name=2790&date=2023-03-31&municipality_id=&route_id=2790_0&direction_id=0&trip_id=p1_2790_0_2%7C1%7C2%7C0915&stop_id=071641&stop_sequence=20
> 
> Paragens p/ verificação de coordenadas: 071639 | En 10 (X) Estação Bobadela | 38.807700 | -9.095520 071641 | En 10 (X) Estação Bobadela | 38.808800 | -9.095020
> 
> Maps: https://www.google.com/maps/place/En+10+(X)+Esta%C3%A7%C3%A3o+Bobadela/@38.8077744,-9.0954299,179a,35y,314.49h,0.28t/data=!3m1!1e3!4m6!3m5!1s0xd192e05d4bca35d:0xb83beaa4b3a6bd46!8m2!3d38.8077!4d-9.09552!16s%2Fg%2F11shqf7jxt
> 
> **Área(s) afetada(s)**
> 
> * [ ]  Área 1 (Viação Alvorada)
> * [x]  Área 2 (Rodoviária de Lisboa)
> * [ ]  Área 3 (TST)
> * [ ]  Área 4 (Alsa Todi)

**Comment by joao-vasconcelos** [comment]
Corrigido.
