### ISSUE TITLE
[A1] Paragens danificadas

### ISSUE THREAD

**Issue by Gasosa12** [carrismetropolitana/gtfs#192]
**Descreva o erro**  

170599 Queluz - Belas (Estação) – A placa foi arrancada

030326 R Elias Garcia 323 – O suporte que segura as placas ao abrigo não está colocado de forma segura, as placas estão viradas ao contrário e em risco de cair a qualquer momento.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Comment by aquint96** [comment]
Boa tarde, o operador confirmou que estas situações já se encontram regularizadas. 
Obrigado pela informação.
