### ISSUE TITLE
[A1 e A3] Paragens duplicadas

### ISSUE THREAD

**Issue by Gasosa12** [carrismetropolitana/gtfs#195]
**Descreva o erro**  
As seguintes paragens estão duplicadas.

060145 e 060029
060147 e 060031
060035 e 060407

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [X] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Comment by inesclemente** [comment]
Olá @Gasosa12, obrigada pelo alerta. A situação já se encontra corrigida e disponível no site.
