### ISSUE TITLE
[A4] Linha 4514 - Headsign errado

### ISSUE THREAD

**Issue by Gasosa12** [carrismetropolitana/gtfs#199]
**Descreva o erro**  
A variante da linha 4514 que inicia em **Loja Nova** e termina em **Canha** aparece com o headsign **Montijo (Terminal Rodoviário)**.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Corrigir o headsign para que apresente o destino **Canha**.

![Inked4514 CNH](https://github.com/carrismetropolitana/gtfs/assets/132413037/0f14867c-b9ba-4f4a-b263-359dbaf321c3)

**Comment by joao-vasconcelos** [comment]
Corrigido nos sistemas, ficará atualizado no site e apps em breve. Obrigado!
