### ISSUE TITLE
[Google Maps] [Área 1] Linhas na paragem aparecem com a paragem atual onde deve ficar o destino

### ISSUE THREAD

**Issue by LaPingvino** [carrismetropolitana/gtfs#2]
**Descreva o erro**  
Várias paragens mostram todos autocarros como se fossem ter o destino da paragem atual

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [x] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Deveriam mostrar o destino/direção do autocarro.

**Screenshots**  
![Screenshot_2023-02-03-12-44-35-592_com.google.android.apps.maps.jpg](https://user-images.githubusercontent.com/10294/216607370-a8001065-7b4a-4ef5-9c15-777c627e6643.jpg)

![Screenshot_2023-02-03-12-48-40-569_com.google.android.apps.maps.jpg](https://user-images.githubusercontent.com/10294/216607427-59487a61-9cbb-4204-9f84-271610724025.jpg)

**Contexto adicional**  
Só parece acontecer na área 1.

**Comment by joao-vasconcelos** [comment]
@LaPingvino mais uma vez muito obrigado por reportar este erro, que foi corrigido com a atualização https://github.com/carrismetropolitana/gtfs/commit/b759dc4b0b8c8cd275dcc0d71ceb0179cfe8e4aa. Será recebido nas plataformas, incluindo Google Maps, durante a noite.

O erro tinha origem numa formatação incorreta do ficheiro `stop_times.txt`.

**Comment by LaPingvino** [comment]
Ainda não aparece corrigido depois de mais que 3 dias, enquanto Google deveria normalmente atualizar em 2...

**Comment by joao-vasconcelos** [comment]
@LaPingvino estamos a aguardar a posição do Google. Aparentemente é necessário uma aprovação manual dos dados. Quando ficar disponível atualizo aqui.

**Comment by LaPingvino** [comment]
Boa. Aguardamos então!

**Comment by LaPingvino** [comment]
Parece que já aprovaram, agora funciona certinho!

**Comment by LaPingvino** [comment]
Este problema voltou @joao-vasconcelos

**Comment by joao-vasconcelos** [comment]
De facto o problema voltou, mas creio que não seja um erro nosso. Essa informação vem da coluna `stop_headsign` do ficheiro `stop_times.txt`. No ficheiro original (CM_GTFS_A1.zip) essa coluna está vazia, e no ficheiro combinado (CarrisMetropolitana.zip) não existe sequer. Quando esse campo está vazio, o sistema deve ler a coluna `trip_headsign` do ficheiro `trips.txt`, que em ambos os ficheiros está corretamente preenchida.

O Google está desde ontem a preparar a alteração para o ficheiro combinado, poderá ser algo temporário do lado deles. Já entrámos em contacto para resolver a situação.

**Comment by joao-vasconcelos** [comment]
Bom dia! Parece estar corrigido. Obrigado 👍
