### ISSUE TITLE
[A3] Cor da linha 3218

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#200]
**Descreva o erro**  
A variante desta linha apresenta uma cor errada

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [X] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Variante Sesimbra (Parque de Campismo) - Sesimbra (Terminal) deve ser cor azul

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/019a44e0-eb1f-401b-9b2b-6de759e186a0)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Corrigido! Obrigado @DiogoBaptista98
