### ISSUE TITLE
[A4] Remover paragens GTFS rodo-Setúbal

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#201]
**Descreva o erro**  
As paragens são antigas da TST desativadas e sem serviços, devem ser removidas 160883 160823 e 160824
A paragem 160883 tem erradamente uma saida da linha 4544 variante Bairro Margaça - Setúbal (Av. 5 de Outubro) que deve passar para a paragem 160139

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Remover 160883 160823 e 160824 
Passar variante da linha 4544 presente na paragem 160883 para a paragem 160139

**Screenshots**  
Se fizer sentido, adicione imagens que ajudem a explicar o problema.

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Corrigido. Obrigado!
