### ISSUE TITLE
[A4] 4443 Destinos trocados

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#203]
**Descreva o erro**  
Titulo dos destinos está trocado na 4443

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/91985388-96a0-47cd-86d1-f691913488cf)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Olá @DiogoBaptista98, corrigido nos sistemas. Atualização no site prevista para o final de Agosto. Obrigado!
