### ISSUE TITLE
[A1] Terminais sem postalete

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#204]
**Descreva o erro**  
Poste dos terminais Carcavelos 050418 e Estoril 050359 estão sem placa.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Colocação de placa

**Screenshots**  
![Imagem WhatsApp 2023-08-18 às 01 31 27](https://github.com/carrismetropolitana/gtfs/assets/54463127/77e61e9a-1c9a-41bb-85fb-044f42cf29cd)
![Imagem WhatsApp 2023-08-18 às 01 31 27](https://github.com/carrismetropolitana/gtfs/assets/54463127/bcf56931-2c2c-4c81-b63e-de82485d628e)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. A situação já está corrigida.
