### ISSUE TITLE
[A1] Postaletes destruidos

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#206]
**Descreva o erro**  
Paragens 120520 e 170765 sem placa de postalete

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
![Imagem WhatsApp 2023-08-25 às 07 15 53](https://github.com/carrismetropolitana/gtfs/assets/54463127/9ca650ef-9802-418c-93d4-57c44eebc0d6)
![Imagem WhatsApp 2023-08-25 às 07 15 56](https://github.com/carrismetropolitana/gtfs/assets/54463127/c7aa2dcd-0ca0-40eb-add9-efb921281c61)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. Temos indicação que a situação já se encontra resolvida.
