### ISSUE TITLE
[A4] Falta paragem R Fazendeiros - Barreiro(Coina)

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#209]
**Descreva o erro**  
As paragens  040138 e 040136 não existem no local, falta o poste, faz sentido as paragens existirem pelo que deve ser alertado o operador para corrigir a situação!

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Colocar paragem física no local

**Screenshots**  
Se fizer sentido, adicione imagens que ajudem a explicar o problema.

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. A situação já se encontra resolvida no terreno.
