### ISSUE TITLE
Melhora GTFS: adicionar só entrada/saída dentro de Lisboa

### ISSUE THREAD

**Issue by LaPingvino** [carrismetropolitana/gtfs#211]
**Descrição**  
A Carris tem exclusividade dentro de Lisboa. Na prática isso significa que dependendo da direção dentro de Lisboa os autocarros ficam só saída ou só entrada. GTFS tem funcionalidade para isto.

**Área(s) afetada(s)**  
A sugestão é relativa a que áreas?

- [x] Área 1 (Viação Alvorada)
- [x] Área 2 (Rodoviária de Lisboa)
- [x] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Comment by joao-vasconcelos** [comment]
Olá @LaPingvino, obrigado pela sugestão. Adicionámos esta informação com o commit https://github.com/carrismetropolitana/gtfs/commit/2434f5b629b99433b994b6fddf0e02e460345b25. É algo que temos feito já há vários meses, após a atualização dos planos. Estamos em testes com o Google para verificar se os campos são lidos corretamente e o planeador sugere as viagens corretas.
