### ISSUE TITLE
[A3, A4] Paragens em Sete Rios

### ISSUE THREAD

**Issue by HenriquPereir** [carrismetropolitana/gtfs#212]
**Descreva o erro**  
As paragens em Sete Rios têm as linhas erradas no site, face à realidade, nomeadamente as P5, P7 e P8 (#060013, #060457, #060458). A paragem P8 tem o postalete errado, indicando uma linha que para no P7 e não ali (a 4730). Também está em falta no site a paragem terminal das linhas em Sete Rios, que não terminam nas paragens de partida, mas sim no recorte situado nas coordenadas 38.7411048, -9.1677820.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [X] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  

- Alterar no site as paragens P5, P7 e P8, para ficarem corretas de acordo com a realidade, assim:
P5 - Linhas 3705 e 3711
P7 - Linhas 3706 e 4730
P8 - Linha 4725
- Pedir à Alsa Todi que troque o postalete da P8 para indicar apenas a 4725, e colocar um postalete na P7 a indicar a 4730.
- Adicionar no GTFS a paragem terminal das linhas de Sete Rios nas coordenadas 38.7411048, -9.1677820, para corresponder à realidade, já que elas não fazem a largada de passageiros nas paragens de partida.

**Screenshots**  
https://imgur.com/AW6Napr
https://imgur.com/LIj7Yw5
https://imgur.com/OmjZR14
https://imgur.com/PE5mmVa

**Contexto adicional**  
A organização das paragens está correta no seguinte documento da Câmara Municipal de Lisboa: https://imgur.com/EclNDft

**Comment by joao-vasconcelos** [comment]
Olá @HenriquPereir, conhecemos a situação e pretendemos corrigir em breve.

A localização e codificação das paragens está correta no GTFS. É necessário atualizar os postaletes e ajustar a informação e desenho dos percursos para bater certo com a realidade.

A paragem de desembarque está criada, no entanto ainda sem percursos associados: https://beta.carrismetropolitana.pt/stops/060459

**Comment by ScriptForAll** [comment]
Boa tarde.

Notei que os nomes das paragens do terminal de Sete Rios não correspondem
