### ISSUE TITLE
[Área 2] Paragens 060221 e 060223 (metro Moscavide) trocadas no gtfs

### ISSUE THREAD

**Issue by LaPingvino** [carrismetropolitana/gtfs#214]
**Descreva o erro**  
Estas paragens se situam um no lugar do outro ao que tá indicado agora.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [x] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
As paragens ficam na sequência contrária, e os dois mais pro lado do primeiro. A localização da segunda paragem agora no mapa é só Carris.

**Screenshots**  
![Screenshot_2023-09-30-14-56-37-131_com.android.chrome.jpg](https://github.com/carrismetropolitana/gtfs/assets/10294/48c37b30-3433-4329-abff-8be084ec1b53)

**Comment by joao-vasconcelos** [comment]
Olá @LaPingvino! Consegues dar um pouco mais de contexto? O que está errado é o ID do GTFS / Postalete? Se trocarmos as paragens de sítio as linhas ficam corretas?

**Comment by LaPingvino** [comment]
as duas paragens ficam no lugar do 060221 em sequência contrária. o 060223 é o lugar da paragem da Carris. por exemplo o 2733 sai da primeira paragem.

**Comment by joao-vasconcelos** [comment]
Consegues confirmar se o assunto ficou resolvido? Deverá estar visível em https://beta.carrismetropolitana.pt/stops/060223. Obrigado!

**Comment by LaPingvino** [comment]
tá perfeito!
