### ISSUE TITLE
Paragens no Barreiro com localidade Alenquer

### ISSUE THREAD

**Issue by LaPingvino** [carrismetropolitana/gtfs#218]
**Descreva o erro**  
As paragens 040153, 040179 e 040151 têm como localidade Alenquer, mas o primeiro é Quinta da Lomba (as demais paragens da Quinta da Lomba ficam generalizadas como Barreiro), segundo é Barreiro e o terceiro é Coina.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [x] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Comment by ScriptForAll** [comment]
Boa tarde, @LaPingvino.

As paragens que têm como localidade "Alenquer" são as que estão previstas para serem apagadas. 
Esta ""propriedade"" está a servir de placeholder para indicar que as paragens irão ser apagadas.

Cumprimentos

**Comment by LaPingvino** [comment]
Isso explica tudo. Contudo, por causa disso também o tempo real indica Alenquer xD.

**Comment by joao-vasconcelos** [comment]
Olá @LaPingvino, a paragem `040153` foi eliminada, a localidade da `040179` foi corrigida e a `040151` está marcada para eliminação. Em breve ficará corrigido no site e no tempo real. Está também planeado fazer uma correção generalizada e mais profunda para as localidades de todas as paragens. Obrigado!
