### ISSUE TITLE
Bug criação PDF: domingo/feriado fica como dia útil em período escolar

### ISSUE THREAD

**Issue by LaPingvino** [carrismetropolitana/gtfs#219]
**Descreva o erro**  
Já tinha no PDF padrão e agora também no livrino pessoal ao menos na linha 4701 e 4551, provavelmente mais linhas. Os dados do dia útil ficam erradamente duplicados na linha de domingos e feriados

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [?] Área 1 (Viação Alvorada)
- [?] Área 2 (Rodoviária de Lisboa)
- [?] Área 3 (TST)
- [x] Área 4 (Alsa Todi)
 
![CarrisMetropolitana - Livro de Horarios (2023-11-17) (2).pdf](https://github.com/carrismetropolitana/gtfs/files/13390507/CarrisMetropolitana.-.Livro.de.Horarios.2023-11-17.2.pdf)

**Comment by inesclemente** [comment]
Olá @LaPingvino, obrigada pelo alerta. Os PDFs já foram novamente gerados.
