### ISSUE TITLE
Linha 2741

### ISSUE THREAD

**Issue by edgarzeferino** [carrismetropolitana/gtfs#22]
Linha 2741.
Aparenta que a linha 2741 está com incoerência entre a sequência das paragens e a indicação do destino. Tanto a origem como o destino indicam "Ericeira" quando a linha 2741 efetua-se entre Ericeira e Lisboa.

![image](https://user-images.githubusercontent.com/33415714/229372401-fd7d463a-78a5-45ba-8602-1797d20ce36d.png)

![image](https://user-images.githubusercontent.com/33415714/229372677-0b061d99-aa2b-4400-8fa7-f6cd48aafe88.png)

![image](https://user-images.githubusercontent.com/33415714/229372596-3842a87f-bd26-4302-ac65-c8049904dd6a.png)

**Comment by joao-vasconcelos** [comment]
Boa tarde @edgarzeferino! Obrigado pelo alerta. Esperamos receber nova versão atualizada e corrigida do operador em breve. Assim que ficar disponível avisamos por aqui.

**Comment by joao-vasconcelos** [comment]
Corrigido!
