### ISSUE TITLE
[Área 4] 4514 tem duas variantes distintas com o mesmo nome

### ISSUE THREAD

**Issue by claudioap** [carrismetropolitana/gtfs#220]
**Descrição**  
Duas das variantes da linha 4514 vão a Pegões, mas uma delas faz um gancho adicional por Afonsos. Tal devia de se refletir no nome da variante dado que atualmente tem nome igual. O nome sugerido é `Canha - Montijo (Terminal Rodoviário) via Pegões e Afonsos` para a variante  `4514_3`. Tal já foi o caso no passado.

**Área(s) afetada(s)**  
- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/5624169/2c05f5f2-32d5-487c-b76a-5a177e3f345a)
![image](https://github.com/carrismetropolitana/gtfs/assets/5624169/0d6eed6c-8611-43fc-b577-9f14cf319c2b)

**Comment by inesclemente** [comment]
Olá @claudioap! Obrigada pelo alerta. Já foi corrigido, em breve ficará disponível no site.
