### ISSUE TITLE
[A1] Circulações da 1512_0 de/via Cemitério de Queluz

### ISSUE THREAD

**Issue by claudioap** [carrismetropolitana/gtfs#221]
**Descrição**  
A variante `1512_0`, nomeada "Queluz (Cemitério) - Montelavar (Largo)" sai do cemitério de Queluz (dirigindo-se para o hospital da Amadora) num dos sentidos, todavia no outro faz o oposto. Dirige-se para o Hospital da Amadora após passar pelo cemitério de Queluz.

Caso isto seja de facto o efetuado, cada um dos sentidos desta variante devia de ser a sua variante.
`Queluz (Cemitério) - Montelavar (Largo)` e `Montelavar (Largo) - Amadora (Hospital) via Queluz (Cemitério)`.

Acredito que o mais simples tanto para a operação como para o passageiro será fazer com que ambos os sentidos tenham inicio/fim no cemitério, circulando ao hospital; ou no hospital, circulando ao cemitério.

**Área(s) afetada(s)**  
A sugestão é relativa a que áreas?

- [x] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/5624169/310e2d74-c7a4-4ef0-86f4-27c111858a01)
![image](https://github.com/carrismetropolitana/gtfs/assets/5624169/39628ccc-54c1-41c6-8c4e-f8a98d911fac)

**Comment by nmaalmeida** [comment]
Esta linha vai deixar de ir ao cemitério a partir do dia 2/1

**Comment by inesclemente** [comment]
Olá @claudioap, obrigada pelo alerta. A linha em questão deixou de ir ao cemitério.
