### ISSUE TITLE
4703 com falta de paragem terminal

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#222]
**Descreva o erro**  
A linha 4703 tem em ambos os sentidos falha na espinha faltando a paragem terminal, este erro leva a que os tempos de viagem entre paragens também se encontrem errados, por exemplo dizendo levar meros 2 minutos a atravessar toda a ponte Vasco da Gama.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
![9A0111A3-DF64-49A6-B671-6D94B77526F1](https://github.com/carrismetropolitana/gtfs/assets/54463127/552b8502-206d-4bc8-b7cd-9938fe6cff94)
![53958B09-803A-4949-8F76-AFBBE6C76758](https://github.com/carrismetropolitana/gtfs/assets/54463127/52bb2f64-6882-40a5-8ac0-13c386ead295)
![AB1AEEEC-FE6E-4FC5-9366-C8DED7E7A9BB](https://github.com/carrismetropolitana/gtfs/assets/54463127/a2e169a6-d244-44a2-a5c4-fb2f5a89a782)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Olá @DiogoBaptista98, obrigado pelo alerta. Vamos corrigir.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta! A linha 4708 já não existe desde o dia 1 de Agosto de 2024.
