### ISSUE TITLE
Área 3: Shape das rotas com erros 

### ISSUE THREAD

**Issue by ricardojorgerm** [carrismetropolitana/gtfs#23]
**Descreva o erro**  
Todas as linhas da área 3 possuem shapes em que todas as paragens se encontram ligadas a todas as restantes paragens

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [x] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Shapes que descrevam o caminho.

**Screenshots**  
<img width="1268" alt="Screenshot 2023-04-03 at 13 44 41" src="https://user-images.githubusercontent.com/4206285/229513492-ff580a0d-e42b-4fff-b6ea-760e7cd5684d.png">

**Comment by joao-vasconcelos** [comment]
Obrigado @ricardojorgerm. Vamos resolver rapidamente.

**Comment by joao-vasconcelos** [comment]
Olá @ricardojorgerm, o erro foi corrigido. Implementámos mais um processo de validação que garante a ordem correta dos pontos das shapes. Foi também adicionado ao site uma função de ordenação dos pontos.
