### ISSUE TITLE
[A2] Colisão de ID de paragem 172538

### ISSUE THREAD

**Issue by ricardojorgerm** [carrismetropolitana/gtfs#234]
**Descreva o erro**  
Uma explicação clara e concisa sobre o erro identificado.

Na Area 2, a paragem 172538 é "Av Fernão Mendes Pinto 96 (Rotunda)" em 38.7799,-9.29005
No ficheiro mestre de stops.txt, a paragem 172538 é R República da Coreia

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [x] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
IDs diferentes

**Screenshots**  
Há várias linhas impactadas por este erro

<img width="1399" alt="image" src="https://github.com/carrismetropolitana/gtfs/assets/4206285/8d5b7233-bfdb-4285-a54c-327c651d387e">

**Comment by ScriptForAll** [comment]
Relevante para #216
