### ISSUE TITLE
A1 - Ranholas - Paragem com o tts_stop_name errado no arquivo stops.txt

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/gtfs#238]
**Descreva o erro**  
A paragem 171889 (R das Cevadinhas (Escola Nac Bombeiros)), tem o tts_stop_name (Rua das Cevadinhas ( Escola Nac Bombeiros )) errado, onde está "Nac" deveria de constar "Nacional"

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

-  Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, corrigir este erro

**Screenshots**  

No Arquivo stops.txt:
![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/72d701dd-7199-459e-bc6c-7681452d9a64)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by ricardojorgerm** [comment]
Vou verificar se é possivel desambiguar sempre Nac -> Nacional para aplicar a correção direta no TTS de forma global

**Comment by ricardojorgerm** [comment]
Infelizmente devido à existencia da Avenida do NAC não posso assumir que o leitor TTS consiga ler Nac como nacional. No entanto irei acrescentar uma correção específica embora recomende à CM que considere corrigir de raiz o nome da paragem para ser mais completo. https://www.openstreetmap.org/#map=19/38.86735/-9.10651

**Comment by joao-vasconcelos** [comment]
Olá @stgarmm, o nome da paragem foi corrigido conforme a sugestão do @ricardojorgerm. Obrigado a ambos pelo alerta e ajuste do código para a desambiguação. Boa semana!

**Comment by stgarmm** [comment]
@joao-vasconcelos de nada!
