### ISSUE TITLE
Localizações e nomes corretos de paragens - Freguesias de Amora e Corroios

### ISSUE THREAD

**Issue by Caziono** [carrismetropolitana/gtfs#24]
**Descreva o erro**  

Informa-se que as seguintes paragens nos GTFS deviam estar nas coordenadas e com os nomes mencionados:
Cruz Pau (Centro) (Av 1º Maio) Rotunda | Paragem 140131: 38.6240198255427, -9.12600260935913
Cruz Pau (R 25 Abril 83) | Paragem 140348: 38.623557969434536, -9.124467740973657
Cruz Pau (R 25 Abril 83) | Paragem 140347: 38.6236693597574, -9.124453986099871
C Pau(Av Marcos Portugal) Farm/Externato | Paragem 140215: 38.62473847238914, -9.12134275838056
C Pau(Av Marcos Portugal) Farm/Externato | Paragem 140583: 38.62418463221322, -9.12129711819079
Amora (R 1º Maio 40) Cemitério | Paragem 140217: 38.627022141294006, -9.118523239686523
Amora (R 1º Maio 40) Cemitério | Paragem 140218: 38.62695844250099, -9.118657910469317
Amora Av Baía Nat Seixal 998 (Seg Soc) | Paragem 140309: 38.62971435166307, -9.117876403611843
Amora Av Baía Nat Seixal 998 (Seg Soc) | Paragem 140310: 38.62959775467582, -9.117646760524057
R Cacheu - Pç Qta do Serrado da Igreja | Paragem 140153: 38.6297068336237, -9.118821860507843
R Cacheu - Pç Qta do Serrado da Igreja | Paragem 140154: 38.62993837405702, -9.11859188400315
Amora R 1º Maio (X) Av Baía Nat Seixal | Paragem 140144: 38.62927811938483, -9.116586296094274
Cruz Pau (R Inf D Augusto N90a) | Paragem 140160: 38.62996152044712, -9.126104907909228
Cruz Pau (R Inf D Augusto N90a) | Paragem 140159: 38.63011455801114, -9.125996985010314
Cruz Pau R Inf D Aug 82) C C Belsul | Paragem 140757: 38.62888746882888, -9.125801363655636
Cruz Pau R Inf D Aug 82) C C Belsul | Paragem 140758: 38.62879006044177, -9.12592801578192
Cruz Pau R Inf D Augusto 74 (Iefp) | Paragem 140161: 38.6279887303645, -9.125887025420559
Cruz Pau (R Inf D Augusto N56) | Paragem 140163: 38.625881796541414, -9.125538493194991
Cruz Pau (R Inf D Augusto N36) | Paragem 140166: 38.62396810428169, -9.125043518396884
Cruz Pau (R Inf D Augusto N36) | Paragem 140165: 38.6242706391887, -9.124981294158271
Paivas (Av Marcos Portugal 49) | Paragem 140522: 38.62348369708805, -9.11791108046591
Paivas (Av Marcos Portugal 49) | Paragem 140521: 38.623332513644996, -9.11824474731161
Amora R Emidio Gui Gar Mendes 29 (Ctt) | Paragem 140311: 38.627519194965, -9.115525463956734 **(A Paragem devia ter o nome "Amora R Emidio Gui Gar Mendes 29" apenas, dado já não existir qualquer loja CTT nas redondezas)**
Amora (R e G G Mendes N12) | Paragem 140345: 38.62696391564817, -9.115274441582889
Amora (R Dr Emidio Gui Gar Mendes 32) | Paragem 140313: 38.624970308182654, -9.11434437678518
Amora (R Dr Emidio Gui Gar Mendes 32) | Paragem 140314: 38.624936706585885, -9.114430617343475
Amora (Av Silva Gomes N78) | Paragem 140219: 38.62593538772269, -9.110382046979213
Amora (Av Silva Gomes N78) | Paragem 140220: 38.62588487717359, -9.110500116179074
Amora (R Fonte Prata) Largo M A Costa | Paragem 140148: 38.62887414680125, -9.112746973757156
Amora (R Fonte Prata) Largo M A Costa | Paragem 140147: 38.62902621028898, -9.113237545248468
Amora (R Operários N28) | Paragem 140297: 38.63062390767059, -9.114749987757726
Amorar Operários15 (X) R P J M Vinagre | Paragem: 140150: 38.63092211202035, -9.115588304246868 **(A Paragem devia ter o nome "Amora Operários15 (X) R P J M Vinagre" para corrigir o erro ortográfico)**
Amora (R Amora Fut Clube) Campo Futebol | Paragem 140151: 38.6324553847493, -9.117909342556326
Amora (R Amora Fut Clube) Campo Futebol | Paragem 140152: 38.63233232732604, -9.117662557886458
Amora (Av Afonso Costa N31) | Paragem 140519: 38.62320204310196, -9.11451883354423
Amora (Av Afonso Costa N31) | Paragem 140520: 38.62311105605698, -9.114587880496945
Amora Av Af Costa (Escola Paulo Gama) | Paragem 140343: 38.62224992671979, -9.11206642812594
Amora Av Afonso Costa 7 Escola | Paragem 140315: 38.621937480798195, -9.111593529332236
Fogueteiro R Mov Forç Arm 95a (C Água) | Paragem 140222: 38.621009860897345, -9.110759573695834
Fogueteiro R Mov Forç Arm 95a (C Água) | Paragem 140221: 38.62082584203944, -9.110604379934015
Fogueteiro (R Mov Forç Arm 22) Farmácia | Paragem 140295: 38.61905520212241, -9.11116488963141
Fogueteiro (R Mov Forç Arm 23) Farmácia | Paragem 140223: 38.618643816154005, -9.111392372018612
Torre Marinha Av Resist Antifas (Escola) | Paragem 140225: 38.61577999413266, -9.108134944484695 **(A Paragem devia ter o nome "Fogueteiro Av Resist Antifas" dado não haver qualquer escola nas redondezas nem estar sequer na localidade de Torre da Marinha)**
Torre Marinha Av Resist Antifas (Escola) | Paragem 140226: 38.61589480002504, -9.108723726958468 **(A Paragem devia ter o nome "Fogueteiro Av Resist Antifas" dado não haver qualquer escola nas redondezas nem estar sequer na localidade de Torre da Marinha)**
Fogueteiro (Av 1º Maio)Posto Combust | Paragem 140113: 38.61615439277182, -9.110726956761393
Fogueteiro (Av 1º Maio) Grémio | Paragem 140129: 38.61674304671001, -9.110885564066495
Fogueteiro (R Gen Humberto Delgado 10) | Paragem 140515: 38.615916721977804, -9.11185453561781
Fogueteiro (Qta Mata) R Roque (Rotunda) | Paragem 140511: 38.6133301373473, -9.112664507121057
R Roque 32 | Paragem 140523: 38.61604718232275, -9.113974113694407
Marco Severino (Av 1º Maio Fte 41) | Paragem 140112: 38.618149088071036, -9.113173994396195
Marco Severino (Av 1º Maio Fte 41) | Paragem 140111: 38.61790334315795, -9.113118168125789
Paivas (Av 1º Maio) Edif Xavier Lima | Paragem 140110: 38.619379104154405, -9.11583239164979
Paivas (Av 1º Maio) Edif Xavier Lima | Paragem 140109: 38.61923668661595, -9.115951399703707
Paivas (Av 1º Maio 17b) | Paragem 140107: 38.620532924599395, -9.11882057533369
Paivas (Av 1º Maio 17b) | Paragem 14010: 38.620567693170734, -9.118438987326563
Cruz Pau (Av 1º Maio 4) | Paragem 140103: 38.62304820474168, -9.1252267990943
Cruz Pau Av Dr Luis Sá (Comércio) | Paragem 140213: 38.62361542171632, -9.126717972757593
Muxito (Av 25 Abril 547) | Paragem 140100: 38.629100361738, -9.133407749244412
Sta M Corroios (Av 25 Abril) Colégio/Mts/Ctt | Paragem 140097: 38.63117232287992, -9.13757572941397
Sta M Corroios (Av 25 Abril) Colégio/Mts/Ctt | Paragem 140098: 38.63127385651975, -9.137539013286961
Sta M Corroios (Av 25 Abril) Posto Abast | Paragem 140095: 38.632362794075, -9.13979875223228
Sta M Corroios (Av 25 Abril) Posto Comb | Paragem 140133: 38.63234494454501, -9.139556112094084
Sta M Corroios (Av 25 Abril) Z Indust | Paragem 140135: 38.63427046591681, -9.143228388487362
Sta Marta Av 25 Abril (Zona Industrial) | Paragem 140093: 38.6346271502391, -9.144126548970203
Qta Princesa (R Cidade Luanda) | Paragem 140763: 38.63375461452065, -9.131850545523747
Qta Princesa (R Cidade Luanda I) | Paragem 140765: 38.633220726162385, -9.129960569095298
Qta Princesa (Arifa) R Cid Maputo | Paragem 140761: 38.632077133667025, -9.130312793779154
Qta Princesa (Arifa) R Cid Maputo | Paragem 140762: 38.63205183982205, -9.130460744018773
Qta Princesa (Qta Paço N17a) | Paragem 140759: 38.630639735992595, -9.126951841240274
Qta Princesa (Qta Paço N17a) | Paragem 140760: 38.63079865325063, -9.126863342161425
Cruz Pau Estr Foros Amora (X) R Soutelo | Paragem 140212: 38.622044867189686, -9.125893784046712
Cruz Pau Estr Foros Amora (X) R Soutelo | Paragem: 140211: 38.62252818885506, -9.125728475005365
Cruz Pau (Estr Foros Amora 37) Mercado | Paragem 140210: 38.619970870566085, -9.125762088109635
Cruz Pau (Estr Foros Amora 37) Mercado | Paragem 140209: 38.62036468563667, -9.125704035854334
R dos Foros Amora 96 (X) Bairro Soutelo | Paragem 140208: 38.61659118260065, -9.125134547566619
R dos Foros Amora 96 (X) Bairro Soutelo | Paragem 140207: 38.61647264983631, -9.125215034794827
Foros Amora (Estr Foros Amora 144) | Paragem 140205: 38.61338858696849, -9.124645755962344
Foros Amora (Estr Foros Amora 204) | Paragem 140202: 38.609734956724324, -9.125022354951398
Foros Amora (Estr Foros Amora 204) | Paragem 140201: 38.6095363098778, -9.124976036953795
Fanqueiro (R Júlio Dinis N3) | Paragem 140199: 38.60838214988608, -9.126914133141012
Fanqueiro (R Júlio Dinis N39) | Paragem 140197: 38.60969966636337, -9.12952965341886
Fanqueiro (R António Sérgio Lte 92) | Paragem 140303: 38.60937645420806, -9.129777301874094
Fanqueiros R António Sérgio 48 (Parque) | Paragem 140195: 38.61031969773853, -9.131561996791257
Fanqueiro (R Azinhaga N169) | Paragem 140191: 38.60734785934503, -9.13366885266782
R Assis Pacheco (X) R Curvo Semedo | Paragem 140659: 38.61760046844957, -9.134497943902488
R Assis Pacheco (X) R Curvo Semedo | Paragem 140660: 38.617573441814045, -9.134607938806441
R A C Monteiro (X) Av Central (Escola) | Paragem 140658: 38.61477545299242, -9.134281006450015
R A C Monteiro (X) Av Central (Escola) | Paragem 140657: 38.61500025871488, -9.134135900303745
Pinhal C Cunha (Av 25 Abril 56) | Paragem 140655: 38.61286000460013, -9.134910729186686
Pinhal C Cunha (R Adolfo C Mteiro 633) | Paragem 140663: 38.6120940809774, -9.135538240803294
Pinhal C Cunha (R Adolfo Cas Mont) 74 | Paragem 140193: 38.61059647539463, -9.134942244112374
Belverde (Av Belverde N14) | Paragem 140190: 38.60368733654539, -9.137817223514219
Belverde (Av Belverde N14) | Paragem 140189: 38.603724194099186, -9.13757203902913
Av Belverde (X) R Iris | Paragem 140187: 38.60114697141661, -9.138946930264687
Belverde (Av Belverde N718) | Paragem 140305: 38.60041489149036, -9.139530472074561
Belverde (Av Belverde 330) | Paragem 140185: 38.59657422122298, -9.142389531095121
Verdizela (Av Res Nat Estuário Sado 11) | Paragem 140182: 38.5904067908185, -9.150784202579532
Verdizela (Av Res Nat Estuário Sado 11) | Paragem 140181: 38.58970106747531, -9.150746079669984
Verdizela (Av Verdizela N5) | Paragem 140177: 38.5825146070589, -9.150375127325253
Verdizela (Av Verdizela N5) | Paragem 140178: 38.58253629981636, -9.150572199156807
Av Verdizela (Centro Comercial) | Paragem 140175: 38.58030703377109, -9.15381897043698
Av Verdizela (Centro Comercial) | Paragem 140176: 38.580178902282256, -9.153655509127923
Verdizela (Av Verdizela N105) | Paragem 140174: 38.57925146964634, -9.157235869761976
Verdizela (Av Verdizela N105) | Paragem 140173: 38.579157269388624, -9.157186697325509
Verdizela (Av Pinhal Aroeira 92) | Paragem 140171: 38.579826805333234, -9.159896019725771
Verdizela (Av Pinhal Aroeira 92) | Paragem 140172: 38.579804566997055, -9.160031069035304
Verdizela (Av Pinhal Aroeira 60) | Paragem 140682: 38.58330361897496, -9.161823578969507
Verdizela (Av Pinhal Aroeira 60) | Paragem 140681: 38.58387520372251, -9.162034759648092

**Situações que requerem uma atenção mais detalhada:**

Av do Mar Belverde (X) Verdizela | Paragem 140183

![image](https://user-images.githubusercontent.com/125212387/229570161-f2ae8d6d-f6f0-4d6b-af79-2cd4985c56b5.png)

Esta paragem provavelmente são na realidade **2 paragens diferentes**, dado que passam aqui linhas nos dois sentidos, todavia isto tem de ser uma situação vista no terreno para ter uma melhor noção.

Foros Amora (Estação) | Paragem 140168

![image](https://user-images.githubusercontent.com/125212387/229575691-75167db5-68d4-42cd-81f8-4453cf2c2d7a.png)

Esta paragem são na realidade **4 paragens diferentes** cada uma com linhas diferentes a fazerem paragem nas mesmas.

A Paragem 1 apenas serve a 3101, enquanto a Paragem 2 serve unicamente a 3108.
Poderei vos dar uma lista exaustiva das linhas que param cada paragem, caso necessitem.

Paivas (R Gomes Freire Andrade 7) | Paragem 140735

![image](https://user-images.githubusercontent.com/125212387/229656749-2944cfc1-9ea0-4460-bcec-6d30191cce89.png)

Esta paragem são na realidade **2 paragens diferentes** servidas pela mesma linha, mas em diferentes sentidos (como assinalado na imagem).

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [X] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Comment by joao-vasconcelos** [comment]
Olá @Caziono, estamos a rever a localização e atributos das paragens município a município em colaboração com o Intermodal. Integrámos recentemente Oeiras e Montijo, aguardamos correções para incluir Seixal e Almada. É possível seguir o progresso deste trabalho aqui: https://docs.google.com/spreadsheets/d/1zi9o57FczWVBQAkQKsZrYl5IAVLQrPelljABrf_ihro/edit#gid=538154677

Devido à dimensão da rede este é um trabalho complexo e demorado, por isso vou fechar este issue uma vez que está a ser acompanhado por outra via.

De qualquer forma iremos utilizar a informação aqui disponbilizada para integrar e corrigir na nossa base de dados.

Muito obrigado!
