### ISSUE TITLE
[A1] 171879 Postalete danificado 

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#240]
**Descreva o erro**  
Paragem 171879 está sem postalete 

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
![318E3648-71BD-452A-9BD5-22E05CF39645](https://github.com/carrismetropolitana/gtfs/assets/54463127/d7496a30-901e-4eeb-aea5-99a7f798db9d)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by JBIMEC** [comment]
Olá @DiogoBaptista98, passei hoje pelo postalete, e o operador já instalou a nova placa!

![Imagem WhatsApp 2024-04-20 às 15 39 06_06838d62](https://github.com/carrismetropolitana/gtfs/assets/162840279/36527c2e-7319-4fa5-8bb4-0e5a000d0362)

**Comment by DiogoBaptista98** [comment]
Situação resolvida
