### ISSUE TITLE
Paragem Marquês Pombal na linha 3708

### ISSUE THREAD

**Issue by LaPingvino** [carrismetropolitana/gtfs#29]
**Descreva o erro**  
A linha 3708 na partida desde Cais do Sodré mostra uma paragem Marquês do Pombal fora do caminho. Imagino que esta não pertença a esta linha.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [x] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Apagar esta paragem nesta linha. (Talvez era a ideia adicionar esta paragem à 3706? seria interessante saber porque acabou aí)

**Screenshots**  
![image](https://user-images.githubusercontent.com/10294/230024545-469438ae-d838-4dc7-99ad-a2a7e836fb18.png)

**Contexto adicional**  
Problema é visível no site e em Moovit, provavelmente aparecerá no Google e CityMapper também nas suas atualizações.

**Comment by LaPingvino** [comment]
![Screenshot_2023-04-11-17-42-39-430_com.google.android.apps.maps.jpg](https://user-images.githubusercontent.com/10294/231232260-e231c65c-0e57-4146-9175-a254716525b1.jpg)

**Comment by joao-vasconcelos** [comment]
Obrigado @LaPingvino, situação corrigida!
