### ISSUE TITLE
Erro das letras nos Cabeçalhos dos PDF's

### ISSUE THREAD

**Issue by JBIMEC** [carrismetropolitana/gtfs#290]
**Descreva o erro**  
Nos primeiros PDF's com as espinhas de cada linhas e os horários, no esquema de origem/destino, no cabeçalho do documento, aparecia a cor da linha (azul, vermelho...) e a letra atribuída a cada tipologia de linha (P, L, R,...). Nestes últimos pdf's, em https://storage.carrismetropolitana.pt/static/pdfs/horarios/ aparece esse mesmo esquema no cabeçalho, com as devidas cores, mas em vez de aparecer a letra atribuída a cada tipologia de linha, aparece só a letra "B"

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

-  Área 1 (Viação Alvorada)
-  Área 2 (Rodoviária de Lisboa)
-  Área 3 (TST)
-  Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
Cabeçalho dos PDF's no ínico da operação:
![image](https://github.com/carrismetropolitana/gtfs/assets/162840279/29892901-159f-4f31-9c21-14efdb9b30d0)
![image](https://github.com/carrismetropolitana/gtfs/assets/162840279/3f39c76b-99dc-45dd-8850-761d0e2d05d6)
![image](https://github.com/carrismetropolitana/gtfs/assets/162840279/84bc6d0f-5ab0-46ce-b644-0b42fe0e28e6)

Cabeçalho dos PDF's em https://storage.carrismetropolitana.pt/static/pdfs/horarios/: (Data de 8 de fevereiro de 2024):
![image](https://github.com/carrismetropolitana/gtfs/assets/162840279/dfd4ec81-3e97-4959-af26-73a9ac7d649f)
![image](https://github.com/carrismetropolitana/gtfs/assets/162840279/94b41693-c9aa-4c4d-8e1d-aaec37307260)
![image](https://github.com/carrismetropolitana/gtfs/assets/162840279/7986bc2c-5ba5-475c-830d-e68af52527ff)
![image](https://github.com/carrismetropolitana/gtfs/assets/162840279/3a819403-73b1-49f2-ac66-69d6c3421c35)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by ttmx** [comment]
Obrigado pelo feedback, irá ser resolvido.

**Comment by JBIMEC** [comment]
Situação resolvida!
Obrigado, @ttmx.
