### ISSUE TITLE
[Google Maps] [Área 3] Linha 3710 tem o lado da rua trocado

### ISSUE THREAD

**Issue by LaPingvino** [carrismetropolitana/gtfs#3]
**Descreva o erro**  
Ao que parece ser toda a extensão da linha, os destinos das paragens da 3710 ficam no lado errado da rua.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [x] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
O destino certo no lado da rua certo. Como mostram os screenshots, o caminho na direção Costa da Caparica mostra Lisboa (Areeiro).

**Screenshots**  
![image](https://user-images.githubusercontent.com/10294/216718329-16137fd7-dea9-48ee-9dd5-5d049b946622.png)
![image](https://user-images.githubusercontent.com/10294/216718440-13308e7f-01f1-4a22-8571-955647784427.png)

**Comment by LaPingvino** [comment]
O mesmo problema acontece no Moovit e no CityMapper, então certamente tem algo trocado no gtfs xD

**Comment by joao-vasconcelos** [comment]
@LaPingvino confirma-se que esta situação já foi corrigida?

**Comment by LaPingvino** [comment]
Pelo que eu vejo agora tá mesmo corrigido, sim :)

**Comment by joao-vasconcelos** [comment]
Boa : ) Obrigado
