### ISSUE TITLE
[A1] - Paragem 030085 com o tts_stop_name errado/incompleto

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/gtfs#300]
**Descreva o erro**  
A paragem "Av Manuel Alped (X) Pcta F Ramos Costa" - **030085**, tem o seu tts_stop_name errado, devido a:
- O leitor de texto não associar "Alped" a "Alpedrinha" (não sei se será possível associar sempre "Alped" a "Alpedrinha";
- E ao leitor de texto não conseguir referir "F" ao nome "Francisco"

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

-  Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/50f7869e-4173-4e4b-83d9-a4807f2aa5c8)
**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by ricardojorgerm** [comment]
Boas,

> E ao leitor de texto não conseguir referir "F" ao nome "Francisco"

Infelizmente, com pena minha, o que sugere não é viável ao nível do leitor de texto, pois podia igualmente ser a Praceta Fernando Ramos da Costa. Quanto a Alpedrinha, farei uma análise para verificar o quão comum é o nome "Manuel Alpedrinha" na toponímia, confesso-lhe que, havendo algumas abreviaturas mais "rebuscadas", como pode entender fará mais sentido corrigir a abreviatura no nome do que corrigir o leitor em si.

**Comment by ricardojorgerm** [comment]
Informo que ['Alped', 'Alpedr', 'Alpedrinha'] são abreviaturas comuns já que Manuel Alpedrinha é um topónimo comum, e por isso serão incluídas no TTS de forma automática.

**Comment by JBIMEC** [comment]
Olá @joao-vasconcelos e @ricardojorgerm, reparei, que na mesma avenida, na 030086, encontra-se também o mesmo erro! Devendo de ser corrigido tal e qual como foi corrigido com a paragem 030085

**Comment by JBIMEC** [comment]
Obrigado pela correção, @joao-vasconcelos!
