### ISSUE TITLE
[A2] 2525 Erros tipograficos

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#309]
**Descreva o erro**  
Uma explicação clara e concisa sobre o erro identificado.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [X] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/b046d75e-7c32-4b43-868f-392898942771)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Olá @DiogoBaptista98, está corrigido. Obrigado
