### ISSUE TITLE
[A1] - Paragens 172495 e 172499 mal posicionadas

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/gtfs#312]
**Descreva o erro**  
Olá, as paragens "Queluz (4 Caminhos)" - `172495` e `172499` estão mal posicionadas no mapa, devendo de ser corrigido conforme está no screenshot abaixo explicado.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

-  Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/18233049-0806-46fa-bbda-dcabc3ce99d6)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Olá @stgarmm, a posição das paragens está a ser corrigida em massa através do [Intermodal](https://editor.intermodal.pt/stops?id=16891). Aqui é possível acompanhar o progresso: https://docs.google.com/spreadsheets/d/1zi9o57FczWVBQAkQKsZrYl5IAVLQrPelljABrf_ihro/edit#gid=538154677
De qualquer forma as posições foram corrigidas e estarão visíveis em breve. Obrigado!

**Comment by stgarmm** [comment]
Obrigado pela informação e atenção!
