### ISSUE TITLE
[A2] - Erros nas Shape's das linhas municipais de Vila Franca de Xira

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/gtfs#319]
**Descreva o erro**  
Olá, reparei que as linhas que a seguir irei indicar, têm uma parte da Shape, que liga a paragem inicial à paragem terminal, diretamente, o que está errado.
As linhas em que se encontram este erro são:

- 2303 - Ambos os sentidos
- 2304 - Ambos os sentidos
- 2306 - Ambos os sentidos
- 2307 - Ambos os sentidos
- 2309 - Ambos os sentidos
- 2310 - Ambos os sentidos
- 2316 - Ambos os sentidos
- 2317 - Ambos os sentidos (nas três variantes)
- 2318 - Ambos os sentidos (nas variantes que não são circulares)
- 2325 - Ambos os sentidos
- 2327 - Ambos os sentidos (na variantes PSI (Est) - Vialonga (Parque Residencial)
- 2328 - Ambos os sentidos
- 2329 - Ambos os sentidos
- 2331 - Ambos os sentidos
- 2333 - Ambos os sentidos

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
-  Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
A parte a eliminar encontra-se circulada.
Exemplo do erro:
![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/a05a6092-739f-44c2-b719-8f657c0cde13)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by LaPingvino** [comment]
Não são só estas linhas, parece ser problema geral na Área 2, por exemplo a 2725 e 2727 fazem o mesmo... No Discord da LPP alguém já identificou que provavelmente há um problema off-by-one no processo.

**Comment by JBIMEC** [comment]
> Não são só estas linhas, parece ser problema geral na Área 2, por exemplo a 2725 e 2727 fazem o mesmo... No Discord da LPP alguém já identificou que provavelmente há um problema off-by-one no processo.

Olá @LaPingvino, abri um novo issue, em que mencionei os problemas já abertos em relação a estes erros nas "Shape's" e expliquei que o mesmo acontecia em todas as linhas que não são nenhuma "Linha Circular" na A2!
O problema é o: #320

**Comment by stgarmm** [comment]
@LaPingvino @JBIMEC já verifiquei que a situação encontra-se resolvida/corrigida!

**Comment by stgarmm** [comment]
Obrigado pela correção!

**Comment by JBIMEC** [comment]
Ok, obrigado pelo aviso!

**Comment by stgarmm** [comment]
@JBIMEC, de nada!
