### ISSUE TITLE
Erro no shape da linha 1247 sentido Fontanelas (Largo)

### ISSUE THREAD

**Issue by ricardojorgerm** [carrismetropolitana/gtfs#32]
**Descreva o erro**  
Existe um troço de quatro paragens que não faz sentido no percurso indicado da linha 1247:

- Casal Cambra (Centro Saúde)
- Av S Tomé e Principe (X) R D Duarte
- R Pedro Álvares Cabral 43 (Casal Cambra)
- Av S Tomé e Principe 25 (Casal Cambra)

Potencialmente existe um problema de IDs duplicados em que as paragens corretas desapareceram do percurso

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [x] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Screenshots**  
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/4206285/230175501-ec8e2856-705c-407d-9561-fef72023a129.png">

**Comment by joao-vasconcelos** [comment]
Olá @ricardojorgerm, prevemos corrigir este erro na próxima semana. Já foi comunicado ao operador. Atualizaremos aqui assim que ficar disponível versão atualizada do GTFS. Obrigado!

**Comment by joao-vasconcelos** [comment]
Corrigido com o commit https://github.com/carrismetropolitana/gtfs/commit/259e7cffb4ca99e3b56e5d1d0cd3ab95e94f5549. Obrigado!
