### ISSUE TITLE
[A2] [A4] 2711 indicado como 21-C, mas na realidade em 17-B / uso duplo de id de paragem

### ISSUE THREAD

**Issue by LaPingvino** [carrismetropolitana/gtfs#323]
**Descreva o erro**  
Os 4720 e 2711 receberam a mesma identificação de paragem, dando a sugestão que ficam na mesma paragem em Oriente, porém a 2711 fica em local físico distinto, cais 17-B. Este lugar fica no momento vazio no mapa.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [x] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Atribuir ID de paragem distinta à paragem do 2711 e separar a descrição para incluir a identificação correta do cais.

**Screenshots**  
![IMG_20240425_142638.jpg](https://github.com/carrismetropolitana/gtfs/assets/10294/e8180edc-4296-48aa-aaff-5d7254bf5132)

![IMG_20240425_142730.jpg](https://github.com/carrismetropolitana/gtfs/assets/10294/b71f0f3a-1a7a-469c-972f-6e717303c544)

![Screenshot_20240425_143329.jpg](https://github.com/carrismetropolitana/gtfs/assets/10294/848d9822-6547-4e75-b51f-aa3197179bf6)

![Screenshot_20240425_143546.jpg](https://github.com/carrismetropolitana/gtfs/assets/10294/515140e5-aa66-43e1-b586-20a4d0a74780)

**Comment by LaPingvino** [comment]
Parece estar corrigido na última atualização de 1 de maio. Vi correto no tempo real paragens no site desde hoje.

**Comment by joao-vasconcelos** [comment]
Olá @LaPingvino, obrigado pelo alerta. Está corrigido sim!
