### ISSUE TITLE
[A1] - Postalete da paragem 050385 sem placa

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/gtfs#324]
**Descreva o erro**  
Olá, o Postalete da paragem "R Carlos Anjos 119A" - `050385`, encontra-se sem a placa que indica qual o nome da paragem, o código e quais as linhas que aqui passam.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [x] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
![Imagem WhatsApp 2024-04-25 às 18 42 33_5e9cfe05](https://github.com/carrismetropolitana/gtfs/assets/158851698/0ecdc3ae-f111-410a-9ee3-d766b2d93505)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by aquint96** [comment]
Tratado
