### ISSUE TITLE
[A3] Titulo linha 3114

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#326]
**Descreva o erro**  
3114 falta o (Estação) ao titulo ficando Foros de Amora **(Estação)** - Paio Pires (Quinta Flamância)
Aplicar alteração também na aba "destino"
Esta denominação incluindo o (Estação) aparece nas rotas 3101 3108 3523 menos na aqui indicada.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [X] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/c321b0d7-6f7b-45b2-b833-5883c4bcf3da)
**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by stgarmm** [comment]
Olá @DiogoBaptista98, o nome já foi alterado conforme sugerido!

![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/8f78c069-8b77-4b37-b416-81efa932fd35)

**Comment by joao-vasconcelos** [comment]
Obrigado!

**Comment by stgarmm** [comment]
De nada
