### ISSUE TITLE
[PDF's] - Linha 1626

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/gtfs#327]
**Descreva o erro**  
Olá, notei que, segundo os PDF's da 1626, passaram a indicar, que a linha mencionada, também passe a ter circulações aos Domingos e Feriados Escolares. É mesmo verdade ou não? Pois, uma pessoa vai ao site, e não aparece lá essa indicação. Tirei como o exemplo o dia de hoje, 1 de maio.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [x] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
**No site:**
![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/aee44ed6-7044-446f-87b3-8db2991b6522)

**No PDF:**
![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/e4ee70ba-09fd-4e71-85d2-cabad58f7c8a)
![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/62ed3556-4fa4-4668-a741-d40b0bdedf66)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by LaPingvino** [comment]
Isto parece-me o bug #219

**Comment by stgarmm** [comment]
Reparei que esta situação já está a ser analisada através do problema carrismetropolitana/pdf-maker#1 !

**Comment by JBIMEC** [comment]
Olá, @stgarmm, informo que o problema associado ao horário da 1626 encontra-se resolvido!:

![image](https://github.com/carrismetropolitana/gtfs/assets/162840279/0ca1dc72-0de9-44ed-9437-4ed2f7e279ca)

![image](https://github.com/carrismetropolitana/gtfs/assets/162840279/b3d5d0e0-f0ae-47cd-b3a1-1cbdd977b67b)

**Comment by stgarmm** [comment]
Obrigado por me informar @JBIMEC. Muito obrigado a quem o resolveu!
