### ISSUE TITLE
[PDF's] - Tempo de passagem em excesso nos horários da A1

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/gtfs#329]
**Descreva o erro**  
Olá, reparei que nos horários da Área 1, datados de 30 de abril de 2024, reparei que no horário da linha 1623, mistura dos tempos de passagem:
- No Período Escolar (Aos Domingos e Feriados)
- No Período de Férias Escolares (Aos Dias Úteis)

Penso que este erro pode acontecer, a nível geral dos horários em PDF da área toda, devido também ao erro que já referi no problema #314 e #327

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [x] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
A Amarelo encontra-se um exemplo:
- **Da mistura aos Domingos e Feriados do Período Escolar:**
![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/aba88ccf-dd5b-49fd-bf31-38e5139da94d)

- **Da mistura aos Dias Úteis do Período de Férias:**
![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/bbb4b907-f113-4b56-b4b3-2e1491ab7724)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by stgarmm** [comment]
Reparei que esta situação já está a ser analisada através do problema carrismetropolitana/pdf-maker#1 !

**Comment by joao-vasconcelos** [comment]
Olá @stgarmm, esta é uma situação que estamos ativamente a resolver. Nestes casos, é suposto que seja adicionada uma legenda que identifica a exceção do horário. Obrigado pelo alerta!
