### ISSUE TITLE
Paragens por ativar

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#33]
Paragens por ativar na A3:
As seguintes duas paragens no GTFS não tem linhas atribuídas:
Possivelmente 3004 3015 e 3019
name=R DA BICA (X) TRA STA TERESA ref=021040
name=R DA BICA 27 ref=021041
![image](https://user-images.githubusercontent.com/54463127/230703816-e71b154f-5b7a-405e-a389-b914e97b4bc3.png)

Possivelmente 3015 e 3019
name=R BORGES CARNEIRO 157 ref=021051
name=R BORGES CARNEIRO 26 ref=021050
name=R MAGALHÃES LIMA 220 ref=021061
name=R MAGALHÃES LIMA 1 ref=021060
![image](https://user-images.githubusercontent.com/54463127/230703393-723ddf53-6d62-448f-b7ec-6e21228444ca.png)

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. A situação já se encontra corrigida e visivel no site.
