### ISSUE TITLE
[A3] - Leitura errada nas paragens 020343 e 020344

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/gtfs#331]
Olá, reparei que o TTS, nas paragens "CH CAPARICA (R ANTANDRADE) PISCINAS MUN" - **020343** e **020344**, em vez de pronunciar "António Andrade", pronuncia "Antandrade". Será por causa das duas palavras não estarem separadas?

![image](https://github.com/carrismetropolitana/tts/assets/158851698/f74dbd90-e5ac-4d68-8443-ce073c2fd620)
![image](https://github.com/carrismetropolitana/tts/assets/158851698/1b34ea3f-f73b-4fd5-8cc0-3d090d8c80b0)

![image](https://github.com/carrismetropolitana/tts/assets/158851698/59c6f551-9322-4d46-8f7a-3326ec8f707f)

**Comment by ricardojorgerm** [comment]
Certamente que sim. Neste caso, como existe uma colisão que se forma entre um final em "t" e um inicio em "a", é fonotaticamente[1] admissível em português a construção ligada de Antandrade embora a palavra seja inválida ("tan" é uma sílaba admissível) e assim, não seria boa prática fazer o tts tentar automaticamente ler separadamente esses elementos. 

@joao-vasconcelos podias passar este bug para o projeto GTFS ou acompanhar de outra forma interna na TML? Pretende-se um espaço entre os caracteres referidos. 

[1] vide https://fonologia.org/fonologia/#fonotatica

**Comment by joao-vasconcelos** [comment]
Corrigido em https://github.com/carrismetropolitana/gtfs/commit/a530589da0a3bc1f113e9e43c6065c2a3f4bfd58
