### ISSUE TITLE
[A4] Horas a faltar ao fim do dia para a linha 4701

### ISSUE THREAD

**Issue by LaPingvino** [carrismetropolitana/gtfs#334]
**Descreva o erro**  
As horas noturnas até a da meia-noite anunciadas não ficaram registadas no GTFS.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
![image](https://github.com/carrismetropolitana/gtfs/assets/10294/ae069043-37a9-4cc2-bf37-7f4cc24a8a5b)

**Screenshots**  
![image](https://github.com/carrismetropolitana/gtfs/assets/10294/5c2936c8-5048-407b-ba95-13a81c186dea)

**Contexto adicional**  
Já foi mencionado no Discord e é capaz que já tenha trabalho para corrigir.

**Comment by LaPingvino** [comment]
Faltam a 21:45, a 23:15 e a 24:00. Faltam de forma parecida para o fds (mas parece que o domingo contém sim a saída das 23:15).

**Comment by ricardojorgerm** [comment]
<img width="593" alt="image" src="https://github.com/carrismetropolitana/gtfs/assets/4206285/605aa38a-ea65-4a90-9a6b-ee4ff23146b0">

Das referidas, parece só faltar a última das 00h00 desde a última atualização (@joao-vasconcelos )

**Comment by LaPingvino** [comment]
Não, nos sábados e domingos ainda falta a hora das 21:45 também, e 23:15 no sábado @ricardojorgerm

**Comment by joao-vasconcelos** [comment]
Olá @LaPingvino, obrigado pelo alerta. Estamos conscientes do erro e aguardamos nova correção por parte do operador. Não consigo estimar uma data para a correção. Não podemos simplesmente adicionar novo horário devido à necessidade de coordenação dos sistemas embarcados e tempo real.

**Comment by LaPingvino** [comment]
A última atualização parece ter corrigido quase tudo, fora da conexão de meia-noite anunciada que não aparece para nenhum dia, o que imagino ser uma coisa entre a TML e a ALSA.

**Comment by LaPingvino** [comment]
De meia-noite estava adicionado até o mudar do mês, agora falta de novo.

**Comment by stgarmm** [comment]
Olá @LaPingvino reparei que o horário das 0h00, já aparece

![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/db2d9e3a-68bf-4255-a99c-bdc98536aa4a)

**Comment by joao-vasconcelos** [comment]
Olá @LaPingvino, obrigado pelo alerta. Em princípio estas situações ficaram corrigidas de vez.
