### ISSUE TITLE
Nomes de paragem

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#34]
As seguintes paragens aparecem nos avisos com nomes diferentes do GTFS
name=R Azinheiras 17-15 ref=140873
Deveria ser Alto Moinho (R das Azinheiras 15)
![image](https://user-images.githubusercontent.com/54463127/230704990-5f347533-0c5c-41f9-9558-abcb7a5616b5.png)

name=Av da Eira ref=020795 ref=020796
Deveria ser Ch Caparica (Av da Eira)
![image](https://user-images.githubusercontent.com/54463127/230705072-34fbb01b-31f9-486b-b520-cd814baf9f68.png)

O nome da paragem ref=140575 Seixalr Silvana Al Cunha (X) Rotunda deve ser Seixal R Silvana Al Cunha (X) Rotunda

ref=010139 e ref=010140
name=AV CANTO DO PINHEIROXR FERNANDO PESSOA deve ser AV CANTO DO PINHEIRO X R FERNANDO PESSOA

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. Estamos a fazer a uniformização da rede, em breve ficará resolvido.
