### ISSUE TITLE
[A3] Linha 3119 numa paragem errada no Fogueteiro.

### ISSUE THREAD

**Issue by galveiap1** [carrismetropolitana/gtfs#340]
**Descreva o erro**  
A linha 3119 no sentido Pinhal Conde da Cunha - Seixal (Terminal Fluvial), está na paragem errada ( #140112 / 38.618150	-9.113171 ), quando é suposto estar no sentido contrário ( #140111 / 38.617928	-9.113142 ), visto que na prática, é onde essa carreira para nesse sentido.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [X] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Screenshots**  
![Captura de ecrã 2024-05-31 161150](https://github.com/carrismetropolitana/gtfs/assets/171360285/f4970e5c-135f-401a-9974-5036746daaa2)

Na screenshot acima, o ponto verde é o local certo que a paragem deve estar, não no outro lado da estrada.

**Comment by susanambb** [comment]
Corrigido!
