### ISSUE TITLE
[A4] - Alterações de JUNHO'24 não aparecem

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/gtfs#345]
**Descreva o erro**  
Olá, reparei que algumas das alterações referentes à área 4, presentes na notícia [Área 4 | Alterações e avisos para junho](https://www.carrismetropolitana.pt/noticias/area-4-alteracoes-e-avisos-para-junho/) não se encontram no GTFS. Refiro-me às alterações de numeração e designação da linha `4405 | Livramento - Montebelo | Circular` e à alteração de percurso, nos paragens e ajustes de horários da linha `4611 | Penalva - Moita (Escola Secundária)`.
Ambas as linhas, deixaram de aparecer na lista de linhas do presentes no site:
`4405`:
![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/621f1dee-7226-40a2-a1d3-6bab1ea240b1)
`4611`:
![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/3acaeedd-8d9f-40cc-87e5-d3e07686745f)

Mesmo procurando pelas novas designações da 4405 (`4481` e `4482`), nenhuma aparece:
![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/5f6319d3-52c2-4114-9bc3-b81bd49d32b3)
![image](https://github.com/carrismetropolitana/gtfs/assets/158851698/58861188-8747-42eb-846a-9349757ed69e)

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [x] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
Se fizer sentido, adicione imagens que ajudem a explicar o problema.

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Olá @stgarmm, as alterações estão em curso. No site beta já estão visíveis: https://beta.carrismetropolitana.pt/lines/4481 e https://beta.carrismetropolitana.pt/lines/4482. A linha 4405 foi separada nestas duas. Deverá aparecer muito em breve no site original. Obrigado!

**Comment by stgarmm** [comment]
De nada, e obrigado por resolverem esta situação @joao-vasconcelos!
Cumprimentos
