### ISSUE TITLE
Ordem de paragens

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#35]
A ordem de paragens da linha 3523  variante Aroeira - Paio Pires (Quinta Flamância) sentido Paio Pires está incorreta.
A paragem CRUZ PAU AV DR LUIS SÁ (COMÉRCIO) vem sempre depois da FOROS AMORA (ESTAÇÃO) por só existir uma paragem no sentido ascentente.
![image](https://user-images.githubusercontent.com/54463127/230705559-4fc67441-8890-4e69-8fc8-ea0c66202bad.png)

![image](https://user-images.githubusercontent.com/54463127/230705466-477ee326-64ad-4076-9510-7b734db02621.png)

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta! Já corrigimos esta situação, e já está visível no site.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta! Já corrigimos esta situação, e já está visível no site.
