### ISSUE TITLE
Paragem inexistente/duplicada.

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#36]
A4 A paragem name=MONTIJO (AV PESCADORES 107) ref=100141 não existe, todas as rotas dessa paragem devem passar para a name=MONTIJO (AV PESCADORES 107) ref=100095

**Comment by DiogoBaptista98** [comment]
Informação adicional:
Foi colocado um poste a mais nas coordenadas 38.706966,-8.979612 duplicando por isso a paragem 100095, mais se afirma que neste arruamento não passa nenhuma rota neste sentido pelo que a paragem nunca poderia ser usada por alguma rota, pede-se por isso que o mesmo seja removido e os horários transferidos para o poste correto.
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/e1f80fc2-0fb0-465a-a7a0-9f6aa1c4a895)

Poste errado em primeiro plano e poste correto em segundo plano.
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/e6916f78-21ef-4c4f-af07-9a895c3c1a29)

Poste correto que contem todas as linhas.
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/a8373338-3fad-4816-954e-ad8316cd3ec7)

**Comment by joao-vasconcelos** [comment]
Corrigido na última atualização. Obrigado!
