### ISSUE TITLE
[A1] - Localidades corretas de algumas paragens (Concelho de Cascais)

### ISSUE THREAD

**Issue by JBIMEC** [carrismetropolitana/gtfs#361]
**Descreva o erro**  
Olá, como no issue #360 referi que algumas paragens tinham as suas localidades erradas, venho aqui neste issue, indicar não só as paragens afetas à linhas mencionadas no issue #360 mas também outras. Sendo isto, as localidade na lista abaixo, devem de ser adicionadas às paragens mencionadas à frente de cada localidade. 

*NOTA* - Paragens da parte ocidente do concelho de Cascais

- [x] Estoril - `050018`, `050022`, `050359`, `050361`, `050363`, `050364`, `050365`, `050366`, `050367`, `050368`, `050369`, `050371`, `050372`, `050373`, `050374`, `050375`, `050376`, `050405`, `050407`, `050409` e `050411`

- [x] Alcoitão - `050191`, `050192`, `050193`, `050194`, `050195`, `050196`, `050199`, `050200`, `050201`, `050202`, `050339`, `050340` e `050341`

- [x] Monte Estoril - `050377`, `050379`, `050381`, `050383`, `050384`, `050399`, `050401`, `050403` e `050413`

- [x] Alcabideche - `050184`, `050185`, `050186`, `050189`, `050190`, `050233`, `050239`, `050351`, `050352`, `050353`, `050354`, `050355` e `050357`

- [x] Amoreira - `050331`, `050332`, `050333`, `050334`, `050335`, `050336`, `050337`, `050338`, `050385`, `050386`, `050387`, `050389`, `050391`, `050393`, `050395` e `050397`

- [x] Carrascal de Alvide - `050225`, `050226`, `050227`, `050228`, `050229`, `050230`, `050231` e `050232`

- [x] Alvide - `050217`, `050218`, `050219`, `050220`, `050221`, `050222`, `050223` e `050241`

- [x] Abuxarda - `050329`, `050330`, `050345` e `050347`

- [x] Fontaínhas - `050211`, `050213`, `050214`, `050215`, `050216`, `050243` e `050245`

- [x] Pai do Vento - `050325`, `050326` e `050327`

- [x] Bº da Cruz Vermelha - `050179` e `050180`

- [x] Bº do Alto da Castelhana - `050321`, `050322`, `050323` e `050324`

- [x] Bº do Alcaide - `050209` e `050210`

- [x] Bicaia - `050293`, `050294`, `050295`, `050296`, `050297`, `050298`, `050299` e `050300`

- [x] Almoínhas Velhas - `050289`, `050290`, `050291` e `050292`

- [x] Malveira da Serra - `050287` e `050288`

- [x] Alcorvim de Cima - `050285` e `050286`

- [x] Alcorvim de Baixo - `050283` e `050284`

- [x] Outeiro do Zambujeiro - `050281` e `050282`

- [x] Charneca - `050279` e `050301`

- [x] Aldeia de Juso - `050275`, `050276`, `050277` e `050303`

- [x] Bº Chesol - `050271`, `050272`, `050273` e `050305`

- [x] Cobre - `050263`, `050265`, `050266`, `050267`, `050669`, `050270`, `050307` e `050309`

- [x] Pampilheira - `050259`, `050260`, `050261` e `050262`

- [x] Bº da Assunção - `050253`, `050255`, `050257`, `050258`, `050311` e `050313`

- [x] Cidadela - `050251`, `050315` e `050317`

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [x] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
Se fizer sentido, adicione imagens que ajudem a explicar o problema.

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Olá @JBIMEC, muito obrigado pela contribuição. O GTFS foi atualizado com as localidades marcadas e deverá estar disponível no site em breve. Obrigado mais uma vez!

**Comment by JBIMEC** [comment]
@joao-vasconcelos de nada!
