### ISSUE TITLE
[A1] - Localidades corretas das paragens 050181 e 050343

### ISSUE THREAD

**Issue by JBIMEC** [carrismetropolitana/gtfs#363]
**Descreva o erro**  
Como referi no issue #360 algumas paragens não tinham a localidade correta.

A paragem `050181`, deverá de ter a localidade de Ribeira da Penha Longa. Já a paragem `050343`, deverá de ter a localidade de Bº da Cadeia do Linhó

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [x] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
Se fizer sentido, adicione imagens que ajudem a explicar o problema.

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Obrigado @JBIMEC! Integrado no GTFS.

**Comment by JBIMEC** [comment]
De nada @joao-vasconcelos ! Obrigado
