### ISSUE TITLE
[A1] - Localidades certas de paragens (Concelho de Sintra)

### ISSUE THREAD

**Issue by JBIMEC** [carrismetropolitana/gtfs#364]
**Descreva o erro**  
Olá, reparei que algumas paragens têm as suas localidades erradas. Na seguinte lista, envio as localidades certas!

_Nota_ - Freguesia de Rio de Mouro

- [x] Varge Mondar - `170409`, `170410`, `170411`, `170412`, `172267`, `172298`, `172269`, e`172270`

- [x] A-dos-Francos - `170413`, `170414`, `170415`, `170416`, `170417`, `170418`, `170419` e `170420`

- [x] Paiões - `170421`, `170422`, `170423`, `170424`,`170425`, `170501`, `172203`, `172204`, `172205`, `172206`, `172207` e `172208`

- [x] Vale Mourão - `170427`, `170428`, `170429`, `170430`, `170433`, `170434`, `170435`, `170436`, `170437`, `170497` e `170499`

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [x] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
Se fizer sentido, adicione imagens que ajudem a explicar o problema.

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Olá @JBIMEC, obrigado mais uma vez!

Acredito que a paragem `172298` não deverá ficar com a localidade "Varge Mondar". Talvez "Linhó"?

**Comment by JBIMEC** [comment]
Olá @joao-vasconcelos, enganei-me a colocar o id de paragem, o id certo é `172268`
