### ISSUE TITLE
Melhorias na linha 4204 4205 e 4503

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#38]
A4 Sugere-se a criação de 4 novas paragens servindo as linhas 4204 4205 e 4503 num percurso longo onde não actualmente não existem, servindo assim melhor a zona industrial do pau queimado e o centro comercial Alegro. Apenas se sugere que a linha 4503 sofra um pequeno ajuste de extensão.
4204 com 4 novas paragens (2 em cada sentido):
![A](https://user-images.githubusercontent.com/54463127/230744033-c9578f50-d3ca-4139-85df-d3521a4dc297.png)
4503 com 4 novas paragens e sendo estendida fazendo terminal na Afonsoeiro (Centro Comercial) 100153 ou 100159:
![AA](https://user-images.githubusercontent.com/54463127/230744051-9a36b49a-affd-488e-bae3-a47ba42e48ef.png)
4205 com 4 novas paragens (2 em cada sentido):
![AAA](https://user-images.githubusercontent.com/54463127/230744059-06a234aa-4027-4ba0-8b52-2366d4e367a1.png)
Esquema das 4 novas paragens a criar
![AAAA](https://user-images.githubusercontent.com/54463127/230744061-49c8f6eb-d16c-4531-b5c3-88e29c6c7228.png)

Locais exatos de introdução das novas paragens, respeita cuidadosamente os cruzamentos e passadeiras existentes facilitando assim a paragem do veiculo e a circulação pedonal do passageiro.

Zona 1 servindo o parque industrial do pau queimado

Estrada do Pau Queimado (Zona Industrial)
![LA1](https://user-images.githubusercontent.com/54463127/230744067-2a342d08-65b3-4bcd-8b72-69197ba27aef.png)

Zona 2 servindo o centro comercial (Alegro)

Rua da Boa Esperança (Centro Comercial)
![LA2](https://user-images.githubusercontent.com/54463127/230744070-c0568ccc-0db6-44d2-8754-42cd1fff75bc.png)

**Comment by DiogoBaptista98** [comment]
Melhorias na 4205 feitas com base em experiencia própria ao ter usado a linha e ter contactado com motoristas.

A linha está mal desenhada e faz inversão de marcha por duas vezes perdendo imenso tempo, no seu percurso final (aqui redesenhado) a linha não tem a proximidade que deveria andando por isso vazia, esta sugestão visa por isso acabar com as duas inversões de marcha poupando esse tempo alargando o percurso de forma a servir mais pessoas e corrigindo o serviço nos bairros periféricos da Atalaia. A ideia proposta garante tambem ligação entre a Atalaia e o Centro Comercial do Montijo que hoje não existe. Estas alterações propostas visam assim tornar a linha eficiente e sustentável.

Os pontos a laranja são paragens existentes a usar, os roxos são paragens novas a criar.
É proposta a desativação das paragens 100165 e 100166 que ficam no meio do nada, sem utilização, em estrada de terra e que obriga autocarros a inverterem marcha para a servir.
Antes
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/25642e77-b80b-4ffc-ab8e-aff98be520d3)
Proposto
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/85a9c7a8-65ff-4d56-836a-b956a2588c73)

**Comment by DiogoBaptista98** [comment]
Passado um ano é inacreditável não haver qualquer resposta que visa corrigir o lastimável desenho das linhas, garantir maior eficiência e melhor servir os passageiros por exemplo acabando com a realidade caricata da paragem Caminho Vaza Borrachas 47.

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98! Obrigada pelo alerta. Já analisámos a situação e verificámos que não existem condições de segurança para colocar as paragens.
