### ISSUE TITLE
[A1] Mudança de serviço 1007

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#394]
**Descreva o erro**  
Pela dimensão da linha 1007 a mesma deveria passar de longa a próxima

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
![image](https://github.com/user-attachments/assets/a020a984-3380-4127-a7c1-5adda1b95ef2)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by aquint96** [comment]
Agradecemos a sugestão.

**Comment by DiogoBaptista98** [comment]
A linha 1007 deixou de existir.
