### ISSUE TITLE
Paragem 170907: linha 1228 consta erradamente

### ISSUE THREAD

**Issue by brazanet** [carrismetropolitana/gtfs#4]
**Descreva o erro**  
Na paragem com o identificador 170907 consta erradamente a linha 1228, alterando o percurso da mesma na representação gráfica.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Na paragem com o identificador 170907 deveriam apenas constar as linhas 1227, 1229, 1236 e 1721.

**Screenshots**  
![image](https://user-images.githubusercontent.com/29508939/217509329-d2a8ca23-fbe8-4fc0-90fa-55638852326c.png)

**Comment by joao-vasconcelos** [comment]
Olá @brazanet, obrigado pelo alerta. O erro foi encaminhado e virá resolvido com a próxima atualização do GTFS.
Peço desculpa pela demora na resposta. Assim que houver novidades sobre este assunto volto ao contacto por aqui.

**Comment by joao-vasconcelos** [comment]
Olá @brazanet, o erro está corrigido no GTFS e atualizado no Google Maps e outras plataformas. Mais uma vez obrigado. Vou dar o assunto como concluído, corrigido pelo commit [31e164d](https://github.com/carrismetropolitana/gtfs/commit/31e164d0a1583809523f03cc25b0ccf659528147)
