### ISSUE TITLE
Paragem por atribuir

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#40]
A1 A paragem 120037 Av Prof Reinaldo Santos (Hosp Sta Cruz) não tem linha associada, faz parte do antigo combus carnaxide, hoje linha 1109. Essa paragem deve ser adicionada após a R Adolfo Casais Monteiro 120471.

![image](https://user-images.githubusercontent.com/54463127/230798698-34997cd6-a8e9-43b6-814a-6e9497bd28ab.png)

**Comment by aquint96** [comment]
Bom dia @DiogoBaptista98, já tinhamos identificado este caso, no próximo GTFS já terá a paragem, obrigado!

**Comment by aquint96** [comment]
@DiogoBaptista98 Esta alteração já se encontra neste GTFS, obrigado.
