### ISSUE TITLE
[A1] Estação do Estoril sem postalete

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#402]
**Descreva o erro**  
Paragem da estação do Estoril não tem postalete 

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
![IMG_2601](https://github.com/user-attachments/assets/51b2b5e9-1b51-4c5e-8085-6c088bc38f60)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by stgarmm** [comment]
Olá, reparei que já colocaram uma nova placa
![17309632229632316937678305844116](https://github.com/user-attachments/assets/04cac4a9-ec00-4cc3-8cde-368bc66daf5c)
