### ISSUE TITLE
Melhorias na linha 1726

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#41]
Inexplicavelmente a linha **1726** sentido Marquês de Pombal passa pela paragem **Estr Almarjão (Rot Estr Mt Cabreira) 30771** sem fazer qualquer paragem sendo por isso uma falha de serviço e um caso caricato para os passageiros que esperam neste abrigo quando o autocarro poderia fazer paragem, para melhor servir a ligação rápida de Algragide-IKEA ao Marquês sugiro por isso colocar a linha 1726 a parar nessa paragem.

![image](https://user-images.githubusercontent.com/54463127/230799267-769d81aa-40ee-44ce-a32b-43c16ad5f528.png)

**Comment by FilipeL1495** [comment]
Esta situação vem desde o tempo que a carreira 13 foi desviada pela Portela.
O argumento da altura incluiu que conceder a referida paragem, iria comprometer o sentido inverso da referida carreira por esta necessitar de efetuar paragem para Queijas no município da Amadora o mais próximo possível a esta o que implicaria um aumento de percurso (ir ao Bairro do Alto do Moinho fazer ganchada).
Outros tempos, outros regulamentos.

Na altura, foi igualmente proposta a variação de percurso da carreira 13N (qual é o número novo?) para circular via CC Alegro em ambos os sentidos, com paragem no local de maior conveniência e que garantisse segurança aos passageiros. No sentido Lisboa torna-se relativamente fácil (paragem no terminal da 1101 ex01) e no sentido Queijas a paragem seria no Leroy Merlin à falta de outra localização.

Nas novas paragens, a carreira faria sempre serviço em Oeiras.

**Comment by aquint96** [comment]
Boa tarde @DiogoBaptista98 obrigado pelo feedback. Esta alteração virá no próximo GTFS, obrigado!

**Comment by aquint96** [comment]
Bom dia, informamos que esta paragem já está em funcionamento desde o dia 2 de maio, apesar de não estar ainda incluida no GTFS (virá no próximo), já foi feito um aviso em como já está ativa.
