### ISSUE TITLE
[A1] Linha 1123 (variante 1123_1)

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/gtfs#427]
**Descreva o erro**  
Olá, reparei que ambas as variantes da linha `1123 | Paço de Arcos (Estação Norte) - Porto Salvo (Lagoas Park)` têm o mesmo nome, devendo de ser adicionado ao nome já existente na variante `1123_1` "via Escolas", para se diferenciar as variantes.
![image](https://github.com/user-attachments/assets/194e65da-b3f2-40c3-950a-9ea958778712)

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [x] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
Se fizer sentido, adicione imagens que ajudem a explicar o problema.

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by aquint96** [comment]
Agradecemos a sugestão.
