### ISSUE TITLE
[A1] - Linha 1119 com destino de variante fora da "área da variante"

### ISSUE THREAD

**Issue by stgarmm** [carrismetropolitana/gtfs#428]
**Descreva o erro**  
Olá, reparei que na variante/viagem `1119_1_` apresenta com título de destino `Leceia (Igreja)`. Esta encontra-se fora da área da variante devido ao nome da variante ser `Leceia (Rotunda Idade Cobre) - Paço De Arcos (Estação Norte)`. Deixo como sugestão então, a variante começar a chamar-se "Leceia (Igreja) - Paço de Arcos (Estação Norte)" e a viagem `1119_1_1` começar a iniciar viagem na paragem `121085`.

Final da viagem `1119_1_2`:
![image](https://github.com/user-attachments/assets/2f44e686-c2be-4247-a307-3d8ab2166a5c)

Sugestão de início da viagem `1119_1_1`:
![image](https://github.com/user-attachments/assets/74537586-e6b3-44cb-86e9-9012cfca2bb6)

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [x] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
Se fizer sentido, adicione imagens que ajudem a explicar o problema.

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by aquint96** [comment]
Agradecemos a sugestão.
