### ISSUE TITLE
Falta paragem

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#43]
A1 Neste local falta uma paragem no GTFS visto que só existem duas no ficheiro e na realidade precisam ser 3, 
1 é a name=Venda Seca ref=170580
2 e 3 só existe um ponto name=Venda Seca ref=170579

![image](https://user-images.githubusercontent.com/54463127/230842980-ec073b7d-d857-49b9-9072-a55f488755c4.png)
O ponto 3 é usado como terminal da linha 1212
![image](https://user-images.githubusercontent.com/54463127/230843487-ee16e9d6-1b5d-4ad6-8e47-7b402135bd25.png)
Porem pelo GTFS também assume paragem das linhas 1512 e 1718 que passam em frente na estrada principal e que deveriam parar no ponto ponto 2 apresentando um afastamento considerado do ponto à rota e que na realidade é muito dificil se se efectuar tal movimento no serviço.
![image](https://user-images.githubusercontent.com/54463127/230843949-058c4755-3396-4de3-a69e-a89a072dac1f.png)

Ou se cria um novo ponto para a 2 e se adiciona a 1512 e 1718 mantendo a ref actual para o terminal 3 ou então assume-se que a atual ref pertence ao ponto 2 e  cria-se um novo ponto para o terminal da linha 1212.

**Comment by aquint96** [comment]
Boa tarde @DiogoBaptista98, obrigado pela informação. Informamos que o ponto 2 não consta como paragem e não irá ser considerada paragem para as linhas 1512 e 1718. Para as linhas 1512 e 1718 irá ser utilizada a paragem com o abrigo, a que está referida na imagem como o ponto 3 com o código 170579. Estas alterações estão previstas serem aplicadas no próximo GTFS, assim como a correção das shapes com as alterações acima descritas.

**Comment by DiogoBaptista98** [comment]
@aquint96 Gostava de perceber se as características do local estão a ser tomadas em consideração pois com a inexistência da paragem 2 e o facto dessa passar para o ponto 3 traz situações de prejuízo e conflito no local.

A paragem 3 encontra-se numa via de serviço perpendicular à estrada  principal sendo que por isso não tem qualquer visibilidade tanto por parte do passageiro na paragem como por parte do motorista que dirige o serviço.

Para a paragem 3 ser servida com qualidade o veiculo terá que obrigatoriamente fazer um caricato desvio para assim verificar a existencia ou não se passageiros, facto que a existencia do ponto 2 como anteriormente existia não implicaria tal desvio obrigatório. 
![image](https://user-images.githubusercontent.com/54463127/234324200-da92aee3-e3c2-4d61-a727-53b5c31dffcb.png)

É este então o percurso obrigatório
![image](https://user-images.githubusercontent.com/54463127/234325196-bd40cacb-10b2-44c6-aa60-5ca6bda9575a.png)
As duas soluções, a anterior sugerida para ser recuperada a vermelho e a suposta atual a azul.
![image](https://user-images.githubusercontent.com/54463127/234325867-b43268e2-2114-4050-a15b-70c0cf11683b.png)
