### ISSUE TITLE
Nome de paragens em sentidos opostos diferentes por um espaço

### ISSUE THREAD

**Issue by Diogo-Paulico** [carrismetropolitana/gtfs#45]
**Descrição**  
Nome da paragem R Alfredo Vitorino Costa 55 que existe nos 2 sentidos tem diferença no nome (um dos sentidos tem um espaço no final), isto está presente nos ficheiro stops.txt do zip da área 2, nas linhas 1157 e 1158. 

**Área(s) afetada(s)**  
- [ ] Área 1 (Viação Alvorada)
- [x] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Comment by joao-vasconcelos** [comment]
Bom dia @Diogo-Paulico, o ficheiro a ser analisado é o [CarrisMetropolitana.zip](https://github.com/carrismetropolitana/gtfs/blob/live/CarrisMetropolitana.zip). É este ficheiro que tem todas as alterações à rede, e o que é publicado para as plataformas. Obrigado
