### ISSUE TITLE
[A1] 1711 sem shape

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#451]
**Descreva o erro**  
1711 sentido caneças sem shape

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida.

**Screenshots**  
![image](https://github.com/user-attachments/assets/e4c29761-76df-4963-ada4-c2b34eb2eb09)
![image](https://github.com/user-attachments/assets/dda8aa2c-e756-432c-b2f2-41aca5a2973b)

**Contexto adicional**  
Adicione qualquer outra informação útil à resolução do problema.

**Comment by joao-vasconcelos** [comment]
Olá @DiogoBaptista98, poderá ter sido uma falha momentânea devido ao cache e alteração do plano em vigor. Está resolvido. Obrigado!
