### ISSUE TITLE
Erro no horário da linha 2803

### ISSUE THREAD

**Issue by certafonso** [carrismetropolitana/gtfs#5]
**Descreva o erro**  
Nos horário da linha 2803, o horário de saída da Ericeira coincide no google maps e no site da carris metropolitana, mas as horas de passagem nas restantes paragens não correspondem (no google maps geralmente o autocarro demora mais tempo a fazer o percurso.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [x] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
Os horários da linha 2803 deviam ser os que constam no site da carris metropolitana, já que este parecem ser os horários praticados.

**Screenshots**  
Exemplo do autocarro das 11:10:
![image](https://user-images.githubusercontent.com/44088727/218491644-bf79d47f-8a51-45cd-9e72-82f59d7b8984.png)

**Comment by joao-vasconcelos** [comment]
Olá @certafonso, obrigado pelo alerta. O Google calcula os seus próprios tempos de passagem/viagem. Esta diferença é particularmente acentuada se o Google considerar que a velocidade do veículo é demasiado alta num determinado troço. Estamos constantemente a atualizar o GTFS e mantemos um diálogo com o Google para tentar corrigir estas situações rapidamente. Assim que houver novidades sobre este tema volto ao contacto.

**Comment by joao-vasconcelos** [comment]
Bom dia @certafonso, a forma de atualizar o feed no Google Maps foi alterada. Poderá demorar até 48h para propagar mas esta questão deve ficar resolvida.

**Comment by certafonso** [comment]
Boas, confirmo que já parece estar resolvido. Obrigado
