### ISSUE TITLE
IDs trocados

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#53]
A4
R DA SOCIEDADE 95 010087 e 010088
Estas duas paragens tem na realidade os ids trocados
![image](https://user-images.githubusercontent.com/54463127/231760359-605e12de-2098-44ce-a6d1-0cc04a1354d8.png)
Paragem Sul R DA SOCIEDADE 95 com o id 010087 no GTFS
![image](https://user-images.githubusercontent.com/54463127/231760647-42334bce-40e3-4a52-830f-f1b7954df95d.png)
Paragem Norte R DA SOCIEDADE 95 com o id 010088 no GTFS
![image](https://user-images.githubusercontent.com/54463127/231761120-6d1a2ff8-55d9-41a4-a097-b6fdc0d3ebe5.png)

Mais quatro com IDs trocados 
Estr Lagoa da Cheia Agropecuária 010049 e 010050
Estr Lagoa da Cheia 610010051 e 010052

É mais pratico trocar diretamente no GTFS sendo preciso tambem trocar os sentidos das linhas que servem

**Comment by joao-vasconcelos** [comment]
Olá @DiogoBaptista98, acredito que este erro já esteja corrigido. Se não estiver peço por favor que o Issue seja re-aberto. Obrigado!
