### ISSUE TITLE
Nome diferente

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#54]
A4 
A paragem 010021 deve ter o nome Passeio Caravelas (Fórum Cult Alcochete) em vez de Passeio Caravelas (Fórum Alcochete) ficando assim de acordo com o postalete local.

![image](https://user-images.githubusercontent.com/54463127/231770702-8971a337-b533-4490-9bb6-a27a98c47571.png)

ref=010057
ref=010058
R FUTEBOL CLUBE S FRANC X R ANT ALEIXO1
R Futebol Clube S Franc X R Ant Aleixo1
deve ser
R FUTEBOL CLUBE S FRANC X R ANT ALEIXO 1
R Futebol Clube S Franc X R Ant Aleixo 1

**Comment by joao-vasconcelos** [comment]
Obrigado @DiogoBaptista98, os nomes serão corrigidos de acordo com novas regras num futuro próximo.
