### ISSUE TITLE
4525 - Erro na espinha GTFS

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#60]
A4
O destino Pinhal novo da linha 4525 não está a funcionar correctamente, aparecendo a espinha e horário do destino oposto. 
![image](https://user-images.githubusercontent.com/54463127/232491375-f85421b7-ddaf-4690-81cc-d1884a17bc7b.png)

**Comment by joao-vasconcelos** [comment]
Olá @DiogoBaptista98, corrigido. Deverá atualizar no site em breve.
