### ISSUE TITLE
Dano grave nas paragens 50391 50333

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#63]
A1 
O postalete da paragem 50391 R Carlos Anjos 820 foi arrancado.

![image](https://user-images.githubusercontent.com/54463127/232598055-f249d577-a4d8-44d1-ab6e-e6a06eb29dec.png)
![image](https://user-images.githubusercontent.com/54463127/232598098-d6ce66a9-dc32-4e4a-8474-960e32ef7ea3.png)
![image](https://user-images.githubusercontent.com/54463127/232598679-f892ceb5-72b3-465a-bab1-e4b81c550e18.png)

Falta o postalete da paragem 50333 Estr da Ribeira 854

![image](https://user-images.githubusercontent.com/54463127/232616032-e88b581b-8c48-4ca4-8817-d509b86e0cf8.png)

**Comment by aquint96** [comment]
Boa tarde @DiogoBaptista98, foi reportado para o operador, obrigado!

**Comment by DiogoBaptista98** [comment]
@aquint96 É possível que tenha havido um lapso. Hoje verifiquei que o problema ainda se encontra presente. Neste sentido penso que o issue talvez faça sentido ficar aberto para já.
![image](https://user-images.githubusercontent.com/54463127/235322242-dc171d7f-3ca1-43f9-b21c-149f8896ddf8.png)
![image](https://user-images.githubusercontent.com/54463127/235322246-516117ed-c789-4840-9b78-2341a85b482e.png)

**Comment by aquint96** [comment]
Bom dia, segundo o operador esta situação já se encontra resolvida, obrigado.
