### ISSUE TITLE
Problemas nas paragens 80973 80961

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#64]
As paragens  80973 80961 estão trocadas no GTFS.

A paragem **Av Sta Bárbara** 80961 deve ficar [38,9368916, -9,3363725] e ter o nome corrigido para **Rua do Castelo (Centro de Saúde)**

A paragem R das Tecedeir**o**s 80973 deve ficar [38,9365347, -9,3360636] e ter o nome corrigido para Rua das Tecedeir**a**s

**Comment by joao-vasconcelos** [comment]
~~@DiogoBaptista98 estas paragens estão trocadas no GTFS ou no terreno? Porque na shape aprecem corretamente.~~ Têm os nomes trocados.

**Comment by joao-vasconcelos** [comment]
Corrigido no GTFS. Nestas situações é mais simples manter o ID e alterar os atributos. Obrigado!

**Comment by DiogoBaptista98** [comment]
> Corrigido no GTFS. Nestas situações é mais simples manter o ID e alterar os atributos. Obrigado!

  De notar que os nomes indicados para correção serão novos e minhas sugestões não correspondendo por isso ao que se encontra atualmente afixado.  @joao-vasconcelos

**Comment by joao-vasconcelos** [comment]
> De notar que os nomes indicados para correção serão novos e minhas sugestões não correspondendo por isso ao que se encontra atualmente afixado. @joao-vasconcelos

O ideal seria no Intermodal estar colocada a informação do postalete real para ser possível depois filtrar pelas diferenças.

**Comment by DiogoBaptista98** [comment]
> > De notar que os nomes indicados para correção serão novos e minhas sugestões não correspondendo por isso ao que se encontra atualmente afixado. @joao-vasconcelos
> 
> O ideal seria no Intermodal estar colocada a informação do postalete real para ser possível depois filtrar pelas diferenças.

Já se encontra registado. Obrigado !
