### ISSUE TITLE
Paragens trocadas 010039 e 010040

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#66]
A4 

As paragens tem o sentido trocado, tanto nas rotas como na posição geográfica, sendo assim deve ser corrigido de forma a ficar assim:

R DOS DAMASCOS 010039 38.748758,-8.945841
R DOS DAMASCOS 010040 38.748707,-8.945941

**Comment by joao-vasconcelos** [comment]
Corrigido. Obrigado!
