### ISSUE TITLE
Várias paragens com nomes diferentes

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#67]
A4
ALCOCHETE (LAGOA LÁPARO) 010035 e 010036 tem nome real de R do Láparo (X) R de Apolo
ALCOCHETE (R LÁPARO X R BRACIEIRA) 010033 e 010034 tem nome real de R do Láparo X R da Bracieira
ALCOCHETE (R LÁPARO) ESTALEIRO MUN 010031 e 010032 tem nome real de R do Láparo (Estaleiro Municipal)
ALCOCHETE (R LÁPARO) SUPERMERCADO 010029 e 010030 tem nome real de R do Láparo (Supermercado)
ALCOCHETE (R CARLOS M ROD FRANCISCO 408) 010027 e 010028 tem nome real de R Carlos M Rodrigues Francisco 408
PQ INDUSTRIAL BATEL (R ALFAZEMAS) 010037 e 010038 tem nome real de R das Alfazemas (Pq Industrial do Batel)
ALCOCHETE (R C M R FRANC 229)ESC MT NOVO 010001 e 010002 tem nome real de R Carlos M Rodri Franc 229 (Esc Mt Novo)
ALCOCHETE (R CIPRIÃO FIGUEIREDO) 010005 tem nome real de R Doutor Ciprião de Figueiredo
ALCOCHETE (R LEITE CUNHA) BIBLIOTECA 010007 e 010008 tem nome real de R Prof Leite da Cunha (Biblioteca Mun)
ALCOCHETE (R Mª TERESA NORONHA) 010025 tem nome real de R Dona Maria Teresa de Noronha
ALCOCHETE (AV RESTAURAÇÃO) EB MANUEL I 010009 e 010010 tem nome real de Av da Restauração (EB D Manuel I)
ALCOCHETE (AV BARRIS) CENTRO SAÚDE 010043 tem nome real de Av dos Barris (Centro de Saúde)
ALCOCHETE (AV D MANUEL I 25) 010017 e 010018 tem o nome real de Av D Manuel I 25
**ALCOCH (AV INF D JOÃO) PRAIA MOINHOS** 010019 (deveria estar **ALCOCHETE (AV INF D JOÃO) PRAIA MOINHOS**) tem o nome rel de Av Infante D João (Praia dos Moinhos)
continua..

**Comment by joao-vasconcelos** [comment]
Olá @DiogoBaptista98, obrigado pelo feedback. O GTFS deve ser a fonte real para os nomes das paragens. Vamos guardar o Issue mas não vamos alterar nomes para já.

**Comment by DiogoBaptista98** [comment]
@joao-vasconcelos acho que não percebeste a issue, os nomes no GTFS é que nao correspondem aos reais e que pela tua regra o deveria. Os nomes presentes no GTFS parece que foram melhorados/alterados.
