### ISSUE TITLE
Erro na linha 4525

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#68]
A4
Erro na paragem R Miguel Bombada 3 130258 sentido Faias 
A paragem R Miguel Bombada 3 130258 não pode aparecer neste sentido antes da escola, ou a paragem correcta é a 130257 ou se de facto faz paragem na indicada (130258) a mesma deve vir depois da escola.

Idealmente ambos os sentidos deveriam ser colocados a fazer paragem nestes dois pontos.
![image](https://user-images.githubusercontent.com/54463127/233077567-fd61c884-496a-42f6-8d9e-a8c251fa18c3.png)

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta! A situação já se encontra corrigida e disponível no site.
