### ISSUE TITLE
PDFs de horario da 2914 e 4730

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#71]
A2
2914
Os sentidos no cabeçalho deste horário estão trocados.
![image](https://user-images.githubusercontent.com/54463127/233120612-034ba95f-23df-4989-a63b-d09cbbb3da39.png)

A4
4730
Esta linha só tem horario no site numa variante e num só sentido faltando por isso os restantes horarios.
![image](https://user-images.githubusercontent.com/54463127/233121691-c5325e6e-7185-47c9-bc17-53b751b0f443.png)

Esta é uma linha longa porém o horário apresenta-se erradamente como rápida. A espinha desta linha está tambem altamente deformada.
![image](https://user-images.githubusercontent.com/54463127/233121910-24134053-0c67-4ed5-84c8-a433605a51db.png)

**Comment by joao-vasconcelos** [comment]
Olá @DiogoBaptista98, prevemos corrigir de fundo esta questão dos PDFs em breve.

**Comment by joao-vasconcelos** [comment]
Corrigido no site.
