### ISSUE TITLE
Paragens duplicadas A3

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#78]
A3
020755 é 020756

HGO HELIPORTO 020757 020758 não existem.

021013 R Conceição Sameiro Antunes 18 - C Sul é duplicada de 020071 Cv Piedade R Sameiro Antunes Farmácia que estão na mesma posição. 38.668000,-9.164574
![image](https://user-images.githubusercontent.com/54463127/233869014-4aca71f4-2848-44c5-9dd9-8aa2b6b1e8e6.png)

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98 ! Obrigada pelo alerta. A situação já se encontra resolvida no terreno e no site.
