### ISSUE TITLE
Horário da 1120

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#80]
Aparentemente o horario da linha 1120 está mais atualizado nas paragens com data de 20/03 do que no site e PDF com a data 20/02. 

![image](https://user-images.githubusercontent.com/54463127/234132400-8a65312c-ea2c-43c2-9960-313c4b95e17d.png)

![image](https://user-images.githubusercontent.com/54463127/234132451-f429239f-94c8-45a6-823a-6b263ba8d42d.png)

**Comment by joao-vasconcelos** [comment]
Vamos corrigir a questão dos PDFs em breve.

(https://github.com/carrismetropolitana/gtfs/issues/71)
