### ISSUE TITLE
Linha 3022 na paragem 020277

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#83]
A3
Falta a linha 3022 no postalete da paragem 020277 como consta na foto abaixo mencionada
![image](https://user-images.githubusercontent.com/54463127/234369653-ee894049-7dcf-4bd5-b42d-bb0e5ab66ed3.png)

**Comment by inesclemente** [comment]
Olá @DiogoBaptista98, obrigada pelo alerta. A situação já está corrigida no terreno.
