### ISSUE TITLE
GTFS-RT

### ISSUE THREAD

**Issue by raulalcampos** [carrismetropolitana/gtfs#86]
**Questão**
Talvez este não seja o método mais eficaz para a minha questão, mas gostaria de saber se existe/está em desenvolvimento algum GTFS-RT ou GEOJSON com a posição dos veículos dos 4 operadores em tempo real (lat/long) e a sua taxa de atualização.

**Área(s) afetada(s)**  
A sugestão é relativa a que áreas?

- [X] Área 1 (Viação Alvorada)
- [X] Área 2 (Rodoviária de Lisboa)
- [X] Área 3 (TST)
- [X] Área 4 (Alsa Todi)

**Comment by LaPingvino** [comment]
De todas as formas está nos planos. Pelo que eu ouvi por meio informal os aparelhos necessários para isto estão para serem instalados já em maio.

**Comment by joao-vasconcelos** [comment]
Olá @raulalcampos, estamos a desenvolver os sistemas para permitir esta funcionalidade. Quando estiver disponível, o acesso será disponibilizado. Obrigado!
