### ISSUE TITLE
Postalete danificado 080016

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#87]
O postalete 080016 fica na A2 mas o mesmo pertencia à linha da A1 por isso em vez de se colocar um postalete duplicado sugiro que coloquem autocolante da 1633 que está em falta.
![image](https://user-images.githubusercontent.com/54463127/235072138-8f68411f-3573-4952-bdbf-98e1baea85f5.png)

**Comment by aquint96** [comment]
Boa tarde, o operador já foi avisado do ato de vandalismo, iraá proceder à colocação de um autocolante no postalete já existente.
Obrigado.

**Comment by aquint96** [comment]
Bom dia, esta alteração já foi efetuada, informação transmitida pelo operador, obrigado.
