### ISSUE TITLE
Nome da paragem 080204

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#88]
A2
O verdadeiro nome desta paragem é R 1º de Maio (X) R Dr Domingos M Pereira e não Mafra (X) C Saúde

![image](https://user-images.githubusercontent.com/54463127/235085102-bb9b3536-0fc7-40cb-9f80-83dd60d4b178.png)

**Comment by joao-vasconcelos** [comment]
Corrigido. Obrigado!
