### ISSUE TITLE
Paragem 071413 demais pro sul no mapa

### ISSUE THREAD

**Issue by LaPingvino** [carrismetropolitana/gtfs#9]
**Descreva o erro**  
A paragem 071413 parece no mapa ao lado do estacionamento do KFC, mas o lugar verdadeiro é ao lado do parque (8CCGQVMM+638).

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [x] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Valor(es) esperado(s)**  
A paragem terá que ficar um pouco mais norte no mapa, ao outro lado da rua de entrada.

**Screenshots**  
![Screenshot_2023-03-18-15-36-28-668_com.citymapper.app.release.jpg](https://user-images.githubusercontent.com/10294/226115839-17b9359a-e198-4357-b2a4-aaf12911b1fa.jpg)

^ eu estou na paragem, o ponto azul.

**Comment by joao-vasconcelos** [comment]
Olá @LaPingvino, localização corrigida! Obrigado 👍
