### ISSUE TITLE
Posição de paragem 050403 

### ISSUE THREAD

**Issue by DiogoBaptista98** [carrismetropolitana/gtfs#90]
A paragem 050403 paragem Av D Nuno Álvares Pereira (Cruzeiro) que serve as linhas 1628 e 1630 no sentido estação do Estoril foi colocada no sitio errado pois encontra-se numa rua por onde não é possível efetuar serviço, deveria por isso ser colocada na localização  38.707133, -9.404113 onde anteriormente existia uma paragem da Scotturb.

![image](https://user-images.githubusercontent.com/54463127/235332389-84d9fad5-155b-4d66-bc26-c992ba34e5e1.png)
![image](https://user-images.githubusercontent.com/54463127/235332340-ed5a7674-6ce4-4c2a-a5d4-513dd2b6c8f0.png)

**Comment by joao-vasconcelos** [comment]
Obrigado @DiogoBaptista98, corrigido!

**Comment by DiogoBaptista98** [comment]
> Obrigado @DiogoBaptista98, corrigido!

@joao-vasconcelos Não me expliquei corretamente. A issue implica tambem a alteração fisica no terreno com a mudança do postalete de local que foi colocado no sitio errado, seria então melhor adicionar "rede fisica" e "aguarda confirmação"?

Foto que demostra que o postalete se encontra no local errado.
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/b3534cb3-1a9c-4a3c-84c6-d44e8c84a2ad)

**Comment by aquint96** [comment]
Boa tarde, passamos a informação ao operador, assim que possível irá proceder à alteração, obrigado.

**Comment by aquint96** [comment]
Boa tarde, informamos que o operador já tem conhecimento da situação e que já realizou a alteração, o problema que temos agora é o facto de o poste já ter sido retirado/vandalizado 2x do local, estamos a avaliar esta situação, obrigado. 
Dou por concluida esta issue.

**Comment by DiogoBaptista98** [comment]
Passadas 3 semanas da ultimo comentário e após ida ao local ontem não foi encontrada nenhuma referencia física à paragem pelo que peço que a issue se abra e se coloque a tag [aguarda confirmação] até resolução da situação . Cumprimentos
![image](https://github.com/carrismetropolitana/gtfs/assets/54463127/75438a07-5fe7-48b7-9b79-e939d7d139a2)
