### ISSUE TITLE
Erro do GTFS em dias feriados

### ISSUE THREAD

**Issue by Caziono** [carrismetropolitana/gtfs#96]
**Descreva o erro**  
Por alguma razão estranha, o GTFS não assume os respetivos horários de dias feriados, quando os mesmos calham em dias úteis ou sábados (mostrando em vez disso, os horários do respetivo dia de semana).

Após verificação no sítio da CMet, vejo que isto só parece acontecer nas áreas mencionadas abaixo.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [X] Área 1 (Viação Alvorada)
- [ ] Área 2 (Rodoviária de Lisboa)
- [X] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Screenshots**  
![image](https://user-images.githubusercontent.com/125212387/235771587-dea5b84f-9b37-4e93-bf06-5ccf948d10b7.png)

![image](https://user-images.githubusercontent.com/125212387/235771812-39ea6f4b-a482-43c9-ac9a-b03051b8f33a.png)

![image](https://user-images.githubusercontent.com/125212387/235771902-0e4c6876-7fdb-4d26-9b47-73dea65b4a0a.png)

![image](https://user-images.githubusercontent.com/125212387/235772662-87be8154-456b-47f7-bf4a-030dbd8be682.png)
Tive de usar o único feriado de maio para ilustrar o exemplo, dado que a Área 4 não tem horários disponíveis em junho.

**Comment by joao-vasconcelos** [comment]
Bom dia @Caziono, obrigado pelo feedback. Este erro deverá estar corrigido com as últimas atualizações.
