### ISSUE TITLE
Nome da linha 2304 com caráteres estranhos

### ISSUE THREAD

**Issue by Caziono** [carrismetropolitana/gtfs#97]
**Descreva o erro**  
Tal como o título menciona, é apenas necessário uma correção ortográfica no sítio da CMet.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [X] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Screenshots**  
![image](https://user-images.githubusercontent.com/125212387/235773883-ad230927-d64b-460e-bc2a-da9782a49996.png)

**Comment by joao-vasconcelos** [comment]
Olá @Caziono, corrigido no GTFS. Obrigado!
